### ISSUE TITLE
hyperledger部署chainco de_example02后可以invoke但是不能query

### ISSUE THREAD

**Issue by dongpengfei** [yeasy/docker-compose-files#10]
query错误信息如下：
```
Error: Error querying chaincode: rpc error: code = 2 desc = Error:Failed to launch chaincode spec(premature execution - chaincode (ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539) is being launched)
````

搭建按照您的blockchain_guide教程进行。

环境：

* 宿主机是centos 7
* 4个docker节点
* 下载的docker是latest版本（0.6版本也是一样）
* pbtf模式

**Comment by yeasy** [comment]
Hi, can you try the image here?

https://hub.docker.com/r/hyperledger/

**Comment by qiang0723** [comment]
有可能是还没deploy好，deploy后等待10-20s，先docker ps 确认下有新的cluster创建成功，再invoke/query试试

**Comment by dongpengfei** [comment]
@qiang0723 

谢谢，昨晚又调试了下，和你的结论应该是一致的，deploy后有延迟（我这边大概有快2min），然后才出现错误。

docker ps后发现应该建好的container的STATUS=exit。

![04p ss6xk7 5 w4d n_puv](https://cloud.githubusercontent.com/assets/1546140/20953210/bb45807c-bc6c-11e6-8d7e-09cc9a2c5111.png)

现在正在查找原因，@qiang0723 @yeasy 有没有什么已知的建议？

**Comment by qiang0723** [comment]
@dongpengfei ,这种情况应该是没建好，中间会有失败 重启的情况，watch -n 1 docker ps 观察等稳定了，这种情况经常发生吗，运行中的容器突然退出？建议docker 版本1.20，docker-compose 1.8.1

**Comment by dongpengfei** [comment]
@qiang0723 

目前为止，我还没有deploy成功过。
最近3天一直在研究，已经重新部署n遍了。

刚才用`watch -n 1 docker ps` 观察了，上面4个节点启动后自己就关闭了。

环境如下：
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by qiang0723** [comment]
换个ubuntu14.04试试？

**Comment by qiang0723** [comment]
@dongpengfei
刚试了下，你把peer-pbft.yml的 CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_ 这个变量注释了试下，我刚试过了，不知道适不适用你，其他操作同 这个项目的[操作说明](https://github.com/yeasy/docker-compose-files/tree/master/hyperledger)

**Comment by dongpengfei** [comment]
@qiang0723 

哦耶哦耶哦耶~~~~哥们谢谢啦

昨天下午我去搭建ubuntu试去了，最后结果依然不行。
我的Centos和Ubuntu都是虚拟机，我担心这个导致，又找了个物理机。。。

今天看到你的留言后我试了下，一次就成功了，部署、查询、转账都成功了。
谢啦！

**Comment by dongpengfei** [comment]
@qiang0723 @yeasy 

那这个是什么导致呢，hyperledger example 中难道还要设置docker的ip？

**Comment by yeasy** [comment]
No, we add more content in the latest doc, hope can help u.

As it's solved, will close first.

Thanks!

**Comment by dongpengfei** [comment]
Yeah, Thanks.
