### ISSUE TITLE
Getting an error while testing SimpleSample Blockchain program from SOAPUI tool

### ISSUE THREAD

**Issue by Senthilmca** [yeasy/docker-compose-files#100]
## Environment
JAVA, BLOCKCHAIN, HYPERLEDGER FABRIC, WINDOWS10, CMD

## How to repeat the problem?
Run the network, register the program, Test the URL from SOAP UI - HTTP:\\LOCALHOST:7050\

## Other Information
Hi All – We are trying to implement Blockchain program using one of the sample program (SimpleSample.JAVA) listed out in the below link. We are able to setup the environment to execute the program in Windows10 operating system. But, when we test it from SOAPUI with URL http:\\localhost:7050 with HTTP METHOD GET/POST, we get an error saying ‘- ERROR GETTING RESPONSE; ORG.APACHE.HTTP.NOHTTPRESPONSEEXCEPTION: THE TARGET SERVER FAILED TO RESPOND’.
Need your inputs on how this can be rectified to run the Blockchain program? The Blockchain program is successfully registered with the Docker. We got stuck post trying from the URL.
Linked followed for the implementation: https://www.ibm.com/developerworks/library/j-chaincode-for-java-developers/index.html
File – SIMPLESAMPLE.JAVA

**Comment by yeasy** [comment]
Sorry, we haven't not tested it under win OS.

Maybe you can ask the questions at https://chat.hyperledger.org/channel/fabric-sdk-java

**Comment by SharanRajani** [comment]
Hello Yeasy, I'm facing the same problem in Linux. Can you please guide me?
