### ISSUE TITLE
Sample node js application which interacts with multiple peers

### ISSUE THREAD

**Issue by nirmal1988** [yeasy/docker-compose-files#101]
## Environment
Any environment information, e.g., os, tool versions, image version.
Windows 10

## How to repeat the problem?
Detailed steps to repeat the problem. 
I made the multiple peers running. now i want to interact with the chain code by using node js application like marbles(https://github.com/IBM-Blockchain/marbles).
Marbles application is using single peer and I tried to modify marbles application to connect with the multiple peers but it did not work. I am getting error like "Endpoing read failed"

## What solutions have u tried?
Potential solutions you have tried, e.g., search Google or restart the computer.
Do you have any sample application which interacts with the chaincode installed on multiple peers/orgs?

## Other Information
Other information u think can help to fix the problem.

**Comment by yeasy** [comment]
Seems irrelevant with this project.
You may need to file an issue at https://github.com/IBM-Blockchain.
