### ISSUE TITLE
ERROR: .IOError:[Error 2] 

### ISSUE THREAD

**Issue by zym566** [yeasy/docker-compose-files#103]
I use $make start then ERROR
ERRPR: .IOError:[Error 2] No such file or directory: /home/ubuntu01/docker-compose-file/hyperledger/1.0/docker-compose-base-e2e.yaml 
Makefile:25: recipe for target start failed 
 make:***[start] Error 1
  
why?thanks

**Comment by yeasy** [comment]
From the error msg, it complains u do not have `/home/ubuntu01/docker-compose-file/hyperledger/1.0/docker-compose-base-e2e.yaml`? Can u have a check?

**Comment by RunshanHu** [comment]
I faced the same problem. This file "docker-compose-base-e2e.yaml" is not in this folder. Where can I get it? Thanks.

**Comment by yeasy** [comment]
Give a quick fix, and close first.

Let me know if there's still problem.
