### ISSUE TITLE
fabric-cli volume mount error

### ISSUE THREAD

**Issue by yang1992** [yeasy/docker-compose-files#105]
## Environment
Any environment information, e.g., os, tool versions, image version.
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 11
Server Version: 17.11.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 89
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.100-boot2docker
Operating System: Boot2Docker 17.11.0-ce (TCL 7.2); HEAD : e620608 - Tue Nov 21 18:11:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.7MiB
Name: default
ID: 5WTH:TCCG:YVMK:RLXR:LU5K:N2EP:ZGLS:FPOA:X6RD:EMJK:XTQM:PAXM
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 43
 Goroutines: 52
 System Time: 2017-11-25T10:27:05.414316644Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://573c6de8.m.daocloud.io/
Live Restore Enabled: false

## How to repeat the problem?
cd docker-compose-files/hyperledger_fabric/1.0.0
make setup
make start

## What solutions have u tried?
Potential solutions you have tried, e.g., search Google or restart the computer.

## Other Information
Other information u think can help to fix the problem.
show error logs:

Starting 3b106c71e231_3b106c71e231_3b106c71e231_3b106c71e231_3b106c71e231_fabric-cli ... error

ERROR: for 3b106c71e231_3b106c71e231_3b106c71e231_3b106c71e231_3b106c71e231_fabric-cli  Cannot start service cli: OCI runtime create failed: container_linux.go:295: starting container process caused "process_linux.go:399: container init caused \"rootfs_linux.go:57: mounting \\\"/Users/yangheng/go/src/github.com/docker-compose-files/hyperledger_fabric/1.0.0/e2e_cli/crypto-config.yaml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/b8c945039c1ca8e969d7d5b5fc21d13c9e8325b50df47166133bd34c75317224\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/b8c945039c1ca8e969d7d5b5fc21d13c9e8325b50df47166133bd34c75317224/etc/hyperledger/fabric/crypto-config.yaml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a dStarting peer1.org2.example.com ... done

ERROR: for cli  Cannot start service cli: OCI runtime create failed: container_linux.go:295: starting container process caused "process_linux.go:399: container init caused \"rootfs_linux.go:57: mounting \\\"/Users/yangheng/go/src/github.com/docker-compose-files/hyperledger_fabric/1.0.0/e2e_cli/crypto-config.yaml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/b8c945039c1ca8e969d7d5b5fc21d13c9e8325b50df47166133bd34c75317224\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/b8c945039c1ca8e969d7d5b5fc21d13c9e8325b50df47166133bd34c75317224/etc/hyperledger/fabric/crypto-config.yaml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
make: *** [start] Error 1

solve solutions:
cd docker-compose-files/hyperledger_fabric/1.0.0, then:
change dir name configtx.yaml to configtx-yaml
change dir name crypto-config.yaml to crypto-config-yaml

change base.yaml volume mount dir name to:
 - ./e2e_cli/configtx-yaml:/etc/hyperledger/fabric/configtx-yaml
 - ./e2e_cli/crypto-config-yaml:/etc/hyperledger/fabric/crypto-config-yaml

**Comment by yeasy** [comment]
Thanks for reporting, the reason seems that we lost the e2e_cli mountable path locally, will fix it soon.

**Comment by gogov5** [comment]
does this issue have been fixed？ thanks ，  I download this code，still have same error.
I follow this guide
https://blog.csdn.net/yeasy/article/details/54928343

**Comment by rameshb444** [comment]
Hyperledger Fabric Balance Transfer Application (1.4.3 version)

I tried to add new org details in fabric-ca-server-config.yaml file and gave that path in docker-compose.yaml file volumes for all 3 orgs ca containers .

volumes:
- ./channel/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
- ../ca-server-config/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml

Restarted the netowrk, but it is showing below error,

**ERROR: for ca.org3.example.com Cannot start service ca.org3.example.com: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\"/home/ubuntu/fabric-samples/newProject/ca-server-config/fabric-ca-server-config.yaml\\" to rootfs \\"/var/lib/docker/overlay2/03d0b6d5e25572670c817f37b1a791938de81835680cce9f11f5d2c0f05d6320/merged\\" at \\"/var/lib/docker/overlay2/03d0b6d5e25572670c817f37b1a791938de81835680cce9f11f5d2c0f05d6320/merged/etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml\\" caused \\"not a directory\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type**

Please suggest on above error and how can i add new org in balance transfer application?
