### ISSUE TITLE
<<区块链原理、设计与应用>>书中提到的代码在项目中找不到,增加了学习难度

### ISSUE THREAD

**Issue by zeroest** [yeasy/docker-compose-files#106]
## Basic Description
在《区块链原理、设计与应用》 9.4.6 基于Docker容器部署，代码在github上不符。增加了学习难度。
如：
```
cd docker-compose-files/hyperledger/1.0   //已经没有`hyperledger`目录
```
```
$ bash scripts/start_fabric.sh docker-compose-2orgs-4peers-event.yaml //没有`start_fabric.sh`文件
```
## Environment
no

## How to repeat the problem?
no

## What solutions have u tried?
尝试在整个项目中都找不到`start_fabric.sh`文件

## Other Information
help

**Comment by yeasy** [comment]
It's updated to https://github.com/yeasy/docker-compose-files/tree/master/hyperledger_fabric/1.0.0.

**Comment by zeroest** [comment]
感谢回复。
