### ISSUE TITLE
hyperledger_fabric/v1.0.5/explorer/config.json is not correct

### ISSUE THREAD

**Issue by AdamsLee** [yeasy/docker-compose-files#109]
## Basic Description
currently,  the first key of 'network-config' is 'orderer'. See hyperledger_fabric/v1.0.5/explorer/config.json :

{
  "network-config": {
	"orderer": [
...
	],
	"org1": {
	  "name": "peerOrg1",
	  "mspid": "Org1MSP",
...

But reads the first org by Object.keys(networkConfig)[0]

https://github.com/hyperledger/blockchain-explorer/blob/master/main.js 
...
var networkConfig = config["network-config"];
var org = Object.keys(networkConfig)[0];
var orgObj = config["network-config"][org];
var orgKey = Object.keys(orgObj);
var index = orgKey.indexOf("peer1");
var peer = orgKey[index];
...

So, I cannot start blockchain-explorer successfully.

## Environment
hyperledger_fabric/v1.0.5

## How to repeat the problem?
read code

## What solutions have u tried?
n/a

## Other Information
n/a

**Comment by yeasy** [comment]
Fixed, pls try again, thanks!
