### ISSUE TITLE
PBFT LedgerError - ResourceNotFound

### ISSUE THREAD

**Issue by rezwan** [yeasy/docker-compose-files#11]
Hi Baohua Yang,
Could you plz invest some time and show me a path......

My assumption is chaincode is not running on PBFT mode
When i run docker-compose up I am getting following errer for my 4 peers
[33mvp0_1         |[0m Error: rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure
and finally on query i am getting LedgerError - ResourceNotFound

**Step to reproduce the error**
I didnt run bash setupPbft.sh as I am on windows docker.
-I manually pulled the necessary images of peer, tagged the images like you sayed
-Took docker-compose-with-membersrvc.yml and peer-pbft.yml to run the images
-Rename docker-compose-with-membersrvc.yml to docker-compose.yml and run docker-compose up
- Then in bash I put three command 
**1.** peer chaincode deploy -u jim -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
**Result** Success
**2.** peer chaincode invoke -l golang -u jim -n ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539  -c '{"Function": "invoke", "Args": ["a", "b", "10"]}'
**Result :** Success
**3.** peer chaincode query -l golang -u jim -n ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539 -c '{"Function": "query", "Args": ["b"]}'
**Result :** Error: Error querying chaincode: rpc error: code = 2 desc = Error:Failed to launch chaincode spec(Could not get deployment transaction for ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539 - LedgerError - ResourceNotFound: ledger: resource not found)
What could be the reason?

.

**Comment by yeasy** [comment]
Hi, currently please do not use windows to run Docker.

And can u try the latest config file?

**Comment by rezwan** [comment]
BIG BIG thanks. You saved my day. It works !!!!!

When I use "ibmblockchain" images everything works perfectly. but when i use "yeasy" images deploying chaincode works in CLI mode but not in RPC call. but invoke and query works in both mode.

**Comment by yeasy** [comment]
Glad it can help u.

There are 3 kinds of images, feel free to have your choice.

Will close this issue first.

Thanks!
