### ISSUE TITLE
Error: got unexpected status: BAD_REQUEST -- 

### ISSUE THREAD

**Issue by phanlong95** [yeasy/docker-compose-files#115]
## Environment
Any environment information, e.g., os, tool versions, image version.

## How to repeat the problem?
Detailed steps to repeat the problem. 

## What solutions have u tried?
Potential solutions you have tried, e.g., search Google or restart the server.

## Other Information
Other information, e.g., how u think may help to fix the problem.

**Comment by phanlong95** [comment]
docker exec -it cli bash

export CHANNEL_NAME=mychannel

peer channel create -o orderer.example.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel.tx --tls $CORE_PEER_TLS_ENABLED --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

when i run this code. 
error: Error: got unexpected status: BAD_REQUEST --
help me. thank you

**Comment by yeasy** [comment]
Pls help post the detailed steps for the problem.

Can you follow the steps in README to test?
