### ISSUE TITLE
v1.1.0 rc1 chaincode instantiate失败  API error (404): {"message":"network v110rc1_default not found"}

### ISSUE THREAD

**Issue by xiaoyzmainkey** [yeasy/docker-compose-files#116]
## Environment
我的环境是：
   docker:17.12.1-ce
   go:1.9.4
   CentOS Linux 7 (Core)
   Hyperledger Fabric x86_64-1.1.0-rc1
## How to repeat the problem?
执行HLF_MODE = kafka make start
执行 make test_channel_create
执行 make test_channel_join
执行 make test_cc_install
以上4步骤都没问题
在执行HML=kafka make test_cc_instantiate
等了大概30S，cli报错：
=== Instantiating chaincode on channel businesschannel... ===
=== chaincodeInstantiate for channel businesschannel on org 1/peer 0 ====
[001 03-13 02:45:16.40 UTC] [github.com/hyperledger/fabric/msp/mgmt] main.Execute.ExecuteC.execute.func1.chaincodeDeploy.InitCmdFactory.GetDefaultSigner.GetLocalMSP -> DEBU Returning existing local MSP
[002 03-13 02:45:16.40 UTC] [github.com/hyperledger/fabric/msp] main.Execute.ExecuteC.execute.func1.chaincodeDeploy.InitCmdFactory.GetDefaultSigner.GetDefaultSigningIdentity.GetDefaultSigningIdentity -> DEBU Obtaining default signing identity
[003 03-13 02:45:16.45 UTC] [github.com/hyperledger/fabric/peer/chaincode] main.Execute.ExecuteC.execute.func1.chaincodeDeploy.instantiate.getChaincodeSpec.checkChaincodeCmdParams -> INFO Using default escc
[004 03-13 02:45:16.45 UTC] [github.com/hyperledger/fabric/peer/chaincode] main.Execute.ExecuteC.execute.func1.chaincodeDeploy.instantiate.getChaincodeSpec.checkChaincodeCmdParams -> INFO Using default vscc
[005 03-13 02:45:16.45 UTC] [github.com/hyperledger/fabric/peer/chaincode] main.Execute.ExecuteC.execute.func1.chaincodeDeploy.instantiate.getChaincodeSpec -> DEBU java chaincode disabled
[006 03-13 02:45:16.45 UTC] [github.com/hyperledger/fabric/msp] main.Execute.ExecuteC.execute.func1.chaincodeDeploy.instantiate.GetSignedProposal.Sign -> DEBU Sign: plaintext: 0AAD070A6D08031A0C08BCF69CD50510...324D53500A04657363630A0476736363 
[007 03-13 02:45:16.45 UTC] [github.com/hyperledger/fabric/msp] main.Execute.ExecuteC.execute.func1.chaincodeDeploy.instantiate.GetSignedProposal.Sign -> DEBU Sign: digest: 0C3763B91016053C7C7F7CBDE8A065BA82503118125547C7CAD1B6EF77B55A71 
Error: Error endorsing chaincode: rpc error: code = Unknown desc = error starting container: API error (404): {"message":"network v110rc1_default not found"}

orderer日志为：
[6f0 03-13 02:37:02.20 UTC] [github.com/hyperledger/fabric/orderer/common/server] handleStream.processStreamingRPC._AtomicBroadcast_Broadcast_Handler.Broadcast -> DEBU Starting new Broadcast handler
[6f1 03-13 02:37:02.20 UTC] [github.com/hyperledger/fabric/orderer/common/broadcast] handleStream.processStreamingRPC._AtomicBroadcast_Broadcast_Handler.Broadcast.Handle -> DEBU Starting new broadcast loop for 172.18.0.14:48736
[6f2 03-13 02:37:02.29 UTC] [github.com/hyperledger/fabric/orderer/common/broadcast] handleStream.processStreamingRPC._AtomicBroadcast_Broadcast_Handler.Broadcast.Handle -> DEBU Received EOF from 172.18.0.14:48736, hangup
[6f3 03-13 02:37:02.29 UTC] [github.com/hyperledger/fabric/orderer/common/server] handleStream.processStreamingRPC._AtomicBroadcast_Broadcast_Handler.Broadcast.func1 -> DEBU Closing Broadcast stream

## What solutions have u tried?
我尝试过将go改成1.8，也不行，docker容器之间通信是正常的，docker引擎日志也没错误。

## Other Information
Other information, e.g., how u think may help to fix the problem.

**Comment by yeasy** [comment]
What is "HLM" and "HML"?

**Comment by xiaoyzmainkey** [comment]
打错了，是HLF_MODE = kafka

**Comment by xiaoyzmainkey** [comment]
我的镜像如下：

REPOSITORY                                                                                              TAG                 IMAGE ID            CREATED             SIZE
dev-peer0.org1.example.com-exp02-1.0-207541cceae707183f8108fcfc8ad03b450411570fb69827d3d40dc2ffdddbb4   latest              f8ef1a12f2a3        2 hours ago         172MB
yeasy/hyperledger-fabric-ca                                                                             1.1.0-rc1           30fff9a2f1f5        7 days ago          874MB
yeasy/hyperledger-fabric-orderer                                                                        1.1.0-rc1           98968e6b2a89        7 days ago          1.06GB
yeasy/hyperledger-fabric-peer                                                                           1.1.0-rc1           8d3aef7c2e1a        7 days ago          1.07GB
yeasy/hyperledger-fabric                                                                                1.1.0-rc1           6ea199967680        8 days ago          1.31GB
yeasy/hyperledger-fabric-base                                                                           1.1.0-rc1           0920eb76feda        8 days ago          1.02GB
hyperledger/fabric-ca                                                                                   x86_64-1.1.0-rc1    8a6c8c2e2ebf        11 days ago         283MB
hyperledger/fabric-tools                                                                                x86_64-1.1.0-rc1    006c689ec08e        11 days ago         1.46GB
hyperledger/fabric-orderer                                                                              x86_64-1.1.0-rc1    10afc128d402        11 days ago         180MB
hyperledger/fabric-peer                                                                                 x86_64-1.1.0-rc1    6b44b1d021cb        11 days ago         187MB
hyperledger/fabric-ccenv                                                                                x86_64-1.1.0-rc1    65c951b9681f        11 days ago         1.39GB
hyperledger/fabric-baseimage                                                                            x86_64-0.4.6        dbe6787b5747        3 weeks ago         1.37GB
hyperledger/fabric-zookeeper                                                                            x86_64-0.4.6        92cbb952b6f8        3 weeks ago         1.39GB
hyperledger/fabric-kafka                                                                                x86_64-0.4.6        554c591b86a8        3 weeks ago         1.4GB
hyperledger/fabric-couchdb                                                                              x86_64-0.4.6        7e73c828fc5b        3 weeks ago         1.56GB
hyperledger/fabric-baseos                                                                               x86_64-0.4.6        220e5cf3fb7f        3 weeks ago         151MB
yeasy/blockchaiREPOSITORY                                                                                              TAG                 IMAGE ID            CREATED             SIZE
dev-peer0.org1.example.com-exp02-1.0-207541cceae707183f8108fcfc8ad03b450411570fb69827d3d40dc2ffdddbb4   latest              f8ef1a12f2a3        2 hours ago         172MB
yeasy/hyperledger-fabric-ca                                                                             1.1.0-rc1           30fff9a2f1f5        7 days ago          874MB
yeasy/hyperledger-fabric-orderer                                                                        1.1.0-rc1           98968e6b2a89        7 days ago          1.06GB
yeasy/hyperledger-fabric-peer                                                                           1.1.0-rc1           8d3aef7c2e1a        7 days ago          1.07GB
yeasy/hyperledger-fabric                                                                                1.1.0-rc1           6ea199967680        8 days ago          1.31GB
yeasy/hyperledger-fabric-base                                                                           1.1.0-rc1           0920eb76feda        8 days ago          1.02GB
hyperledger/fabric-ca                                                                                   x86_64-1.1.0-rc1    8a6c8c2e2ebf        11 days ago         283MB
hyperledger/fabric-tools                                                                                x86_64-1.1.0-rc1    006c689ec08e        11 days ago         1.46GB
hyperledger/fabric-orderer                                                                              x86_64-1.1.0-rc1    10afc128d402        11 days ago         180MB
hyperledger/fabric-peer                                                                                 x86_64-1.1.0-rc1    6b44b1d021cb        11 days ago         187MB
hyperledger/fabric-ccenv                                                                                x86_64-1.1.0-rc1    65c951b9681f        11 days ago         1.39GB
hyperledger/fabric-baseimage                                                                            x86_64-0.4.6        dbe6787b5747        3 weeks ago         1.37GB
hyperledger/fabric-zookeeper                                                                            x86_64-0.4.6        92cbb952b6f8        3 weeks ago         1.39GB
hyperledger/fabric-kafka                                                                                x86_64-0.4.6        554c591b86a8        3 weeks ago         1.4GB
hyperledger/fabric-couchdb                                                                              x86_64-0.4.6        7e73c828fc5b        3 weeks ago         1.56GB
hyperledger/fabric-baseos                                                                               x86_64-0.4.6        220e5cf3fb7f        3 weeks ago         151MB
yeasy/blockchain-explorer                                                                               0.1.0-preview       d3d781c8c96b        2 months ago        659MB
n-explorer                                                                               0.1.0-preview       d3d781c8c96b        2 months ago        659MB

**Comment by yeasy** [comment]
Can u try this

`HLF_MODE = kafka make`

which will run the entire testing with kafka mode automatically.

If you do not have the `HLF_MODE = kafka` before the cmd, then it's default to solo mode.
