### ISSUE TITLE
How can I enable REST api service in hyperledger fabric 1.0 preview environment?

### ISSUE THREAD

**Issue by allegewhd** [yeasy/docker-compose-files#12]
Hi, yeasy, thanks for the great job of this project.I followed hyperledger/1.0/README.md, and run `go/chaincode_example02` by peer command successfully. But when I tried to access some REST api endpoint, orderer service always refused those http connection immediately. 
```
transport: http2Server.HandleStreams received bogus greeting from client: .....
```
I am wondering how can share fabric-ca enroll session with peer proccess, sounds like fabric-ca server listenning port 8888, but peer server proccess do not communicate with this port. Is the reason that v1.0 is still on developing, integration part is not implemented yet?

**Comment by allegewhd** [comment]
(Continued), grpc think those connection as rogus connection. I am wondering how can share fabric-ca enroll session with peer proccess, sounds like fabric-ca server listenning port 8888, but peer server proccess do not communicate with this port. Is the reason  that v1.0 is still on developing, integration part is not implemented yet?

**Comment by yeasy** [comment]
hi, in fabric peers, the rest api will be deprecated, and only support grpc connection.
for fabric-ca, the port 8888 is actually from the cfssl. Recently the grpc port is updated to 7054.

**Comment by rezwan** [comment]
from my website i want to invoke,deploy or query. In my case if rest call doesnt work how can I communicate with chain code ? any example will be appreciated.

**Comment by yeasy** [comment]
You have to use the client or SDK.

See http://hyperledger-fabric.readthedocs.io/en/latest/gettingstarted/

**Comment by allegewhd** [comment]
Thanks yeasy, I'll try some SDK samples. But still wondering how to integrate fabric-ca with orderer and peer process just like member service in v0.6. Hope that `hyperledger_code_fabric` project will be helpful:)

**Comment by rezwan** [comment]
Thanks a lot. The  upper link works perfectly in CLI mode. I followed all the instruction but when I call "node deploy.js" command it returns error from hackfest/node_modules/elliptic/lib/elliptic/ec/index.js file line 94:key = this.keyProfomPrivate(key,enc) returns null . May be this is because of certificate related error. What could be the reason....

**Comment by yeasy** [comment]
suggest u post the problem to the node sdk channel.

chat.hyperledger.org

**Comment by rezwan** [comment]
Yes I will try to find solution from there. Thanks

**Comment by nbkesavan** [comment]
Hi Yeasy,
Did you got  any solution regarding the REST API .

**Comment by yeasy** [comment]
No, in 1.0, we do not support rest api feature.

**Comment by nbkesavan** [comment]
Thanks Year.
Is there any other alternate API to communicate with peer from web application

**Comment by yeasy** [comment]
The sdk is the only way.

See https://wiki.hyperledger.org/projects/cello, which can work with sdk-py together.

**Comment by yeasy** [comment]
@kmohanar certainly depends on the application language.

**Comment by kmohanar** [comment]
Is there any technical document/steps which explain how to make cello and sdk-py together to interact with the yeasy docker images. If so, Please share with us.

**Comment by archimonde1581** [comment]
When i test a gateway for baas platform ,it gives me a error message that :'no channel peers configured for channel'
