### ISSUE TITLE
make test_cc_install sometimes fails with v1.2 - need to rerun it few times to succeed

### ISSUE THREAD

**Issue by ng2dev** [yeasy/docker-compose-files#123]
Note: 
              If it happens it happens on a random peer of the 4 and 
              it does not seem to happen with previous versions, only 1.2 seems to hang at times

Error:
core@blockchain-templates ~/docker-compose-files/hyperledger_fabric/v1.2.0 $ make test_cc_install
Install chaincode on the fabric network
=== Installing chaincode exp02 on all 4 peers... ===
=== Install Chaincode exp02:1.0 (examples/chaincode/go/chaincode_example02) on org 1/peer 0 === 
=== Chaincode is installed on remote peer0 === 
=== Install Chaincode exp02:1.0 (examples/chaincode/go/chaincode_example02) on org 1/peer 1 === 
[001 08-20 15:00:39.39 UTC] [github.com/hyperledger/fabric/peer/chaincode] main.Execute.ExecuteC.execute.func1.chaincodeInstall.genChaincodeDeploymentSpec.getChaincodeSpec.checkChaincodeCmdParams -> INFO Using default escc
[002 08-20 15:00:39.39 UTC] [github.com/hyperledger/fabric/peer/chaincode] main.Execute.ExecuteC.execute.func1.chaincodeInstall.genChaincodeDeploymentSpec.getChaincodeSpec.checkChaincodeCmdParams -> INFO Using default vscc
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f68e64327f8]

runtime stack:
runtime.throw(0x106be8c, 0x2a)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0xcb934b, 0xc42007ca98, 0x106a17b)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc42007ca50 sp=0xc42007ca18 pc=0x402314
os/user._Cfunc_mygetpwuid_r(0x1f4, 0xc4203e2f30, 0x7f68d40008c0, 0x400, 0xc42000ea50, 0x0)
	_cgo_gotypes.go:170 +0x4d fp=0xc42007ca98 sp=0xc42007ca50 pc=0x8ed0dd
os/user.lookupUnixUid.func1.1(0x1f4, 0xc4203e2f30, 0x7f68d40008c0, 0x400, 0xc42000ea50, 0xc42007cb28)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:100 +0x13f fp=0xc42007cad8 sp=0xc42007ca98 pc=0x8eecbf
os/user.lookupUnixUid.func1(0x10)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:100 +0x50 fp=0xc42007cb18 sp=0xc42007cad8 pc=0x8eed60
os/user.retryWithBuffer(0xc4203248d0, 0xc42007cc08, 0xc4203248d0, 0xf9b000)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:253 +0x3b fp=0xc42007cb78 sp=0xc42007cb18 pc=0x8ee18b
os/user.lookupUnixUid(0x1f4, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x130 fp=0xc42007cc40 sp=0xc42007cb78 pc=0x8ed610
os/user.lookupUserId(0xc4200f15c0, 0x3, 0x0, 0x482444, 0x1f4)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:86 +0x73 fp=0xc42007cc78 sp=0xc42007cc40 pc=0x8ed4a3
os/user.LookupId(0xc4200f15c0, 0x3, 0x3, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup.go:41 +0x51 fp=0xc42007ccc8 sp=0xc42007cc78 pc=0x8ecaa1
archive/tar.statUnix(0x11324a0, 0xc42001d5f0, 0xc420109340, 0x1960280, 0x106)
	/usr/local/go/src/archive/tar/stat_unix.go:39 +0x4c1 fp=0xc42007cd48 sp=0xc42007ccc8 pc=0x8f87d1
archive/tar.FileInfoHeader(0x11324a0, 0xc42001d5f0, 0xc4200818f0, 0x62, 0x0, 0x0, 0x7f68e77c2c90)
	/usr/local/go/src/archive/tar/common.go:699 +0x491 fp=0xc42007cec8 sp=0xc42007cd48 pc=0x8f1ca1
github.com/hyperledger/fabric/core/container/util.WriteStreamToPackage(0x1116840, 0xc42031d2c0, 0xc4200818f0, 0x62, 0xc420081922, 0x30, 0xc42044f500, 0x30, 0x4afa01)
	/go/src/github.com/hyperledger/fabric/core/container/util/writer.go:180 +0x18b fp=0xc42007d080 sp=0xc42007cec8 pc=0x9862cb
github.com/hyperledger/fabric/core/container/util.WriteFileToPackage(0xc4200818f0, 0x62, 0xc420081922, 0x30, 0xc42044f500, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/core/container/util/writer.go:170 +0x3aa fp=0xc42007d198 sp=0xc42007d080 pc=0x98609a
github.com/hyperledger/fabric/core/chaincode/platforms/golang.(*Platform).GetDeploymentPayload(0x1984938, 0xc4203eb5c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/core/chaincode/platforms/golang/platform.go:467 +0x1331 fp=0xc42007d9a8 sp=0xc42007d198 pc=0x98dd81
github.com/hyperledger/fabric/core/chaincode/platforms.GetDeploymentPayload(0xc4203eb5c0, 0xc4203eb5c0, 0x0, 0x0, 0x0, 0xc420591500)
	/go/src/github.com/hyperledger/fabric/core/chaincode/platforms/platforms.go:80 +0x89 fp=0xc42007d9f0 sp=0xc42007d9a8 pc=0x992d29
github.com/hyperledger/fabric/core/container.GetChaincodePackageBytes(0xc4203eb5c0, 0x0, 0x0, 0xc4203e26c0, 0xc4200f0e06, 0x6)
	/go/src/github.com/hyperledger/fabric/core/container/controller.go:203 +0x96 fp=0xc42007da38 sp=0xc42007d9f0 pc=0xc2e7f6
github.com/hyperledger/fabric/peer/chaincode.getChaincodeDeploymentSpec(0xc4203eb5c0, 0xc4203eb501, 0x0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/peer/chaincode/common.go:64 +0x112 fp=0xc42007daa0 sp=0xc42007da38 pc=0xc4abb2
github.com/hyperledger/fabric/peer/chaincode.genChaincodeDeploymentSpec(0xc4200e1200, 0x7ffc42c6f718, 0x5, 0x7ffc42c6f721, 0x3, 0x0, 0x0, 0xc42007dc70)
	/go/src/github.com/hyperledger/fabric/peer/chaincode/install.go:104 +0xab fp=0xc42007db68 sp=0xc42007daa0 pc=0xc51e3b
github.com/hyperledger/fabric/peer/chaincode.chaincodeInstall(0xc4200e1200, 0x0, 0x0, 0xc4205a71e0, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/peer/chaincode/install.go:172 +0x15c fp=0xc42007dc58 sp=0xc42007db68 pc=0xc525bc
github.com/hyperledger/fabric/peer/chaincode.installCmd.func1(0xc4200e1200, 0xc42053d140, 0x0, 0x6, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/peer/chaincode/install.go:44 +0x54 fp=0xc42007dc98 sp=0xc42007dc58 pc=0xc57804
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200e1200, 0xc42053d080, 0x6, 0x6, 0xc4200e1200, 0xc42053d080)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:698 +0x46d fp=0xc42007dd40 sp=0xc42007dc98 pc=0xc191dd
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1876320, 0x19607b0, 0xf, 0x1)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:783 +0x2e4 fp=0xc42007de70 sp=0xc42007dd40 pc=0xc19954
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute(0x1876320, 0x1, 0xffffffffffffffff)
	/go/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:736 +0x2b fp=0xc42007dea0 sp=0xc42007de70 pc=0xc1964b
main.main()
	/go/src/github.com/hyperledger/fabric/peer/main.go:97 +0x5bf fp=0xc42007df88 sp=0xc42007dea0 pc=0xcb7edf
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc42007dfe0 sp=0xc42007df88 pc=0x42e0a2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42007dfe8 sp=0xc42007dfe0 pc=0x45bce1

goroutine 7 [syscall]:
os/signal.signal_recv(0xc420057fc8)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 9 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc420459830)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:109 +0x182
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:95 +0x3f

goroutine 10 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc4205fbb80)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x14a
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14c

goroutine 11 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420456b40)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:1243 +0x235
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420456b40)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:854 +0x1b5
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:845 +0xe1

goroutine 18 [IO wait]:
internal/poll.runtime_pollWait(0x7f68e77c2f00, 0x72, 0xc420547970)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420489018, 0x72, 0xffffffffffffff00, 0x111a740, 0x1899400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420489018, 0xc420101c00, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420489000, 0xc420101c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc420489000, 0xc420101c00, 0x400, 0x400, 0x8, 0x8, 0x3f3)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e7c0, 0xc420101c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42044c1b0, 0x7f68e77e3ed0, 0xc42000e7c0, 0x5, 0xc42000e7c0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc42044e000, 0x1097417, 0xc42044e120, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc42044e000, 0xc42021e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc42044a600, 0xc4201089d8, 0x9, 0x9, 0x30, 0x28, 0xf83d40)
	/usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1116840, 0xc42044a600, 0xc4201089d8, 0x9, 0x9, 0x9, 0xc420547df0, 0x400ece, 0xc420547e9f)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x1116840, 0xc42044a600, 0xc4201089d8, 0x9, 0x9, 0x85e574, 0xc42044d200, 0xc420440004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.readFrameHeader(0xc4201089d8, 0x9, 0x9, 0x1116840, 0xc42044a600, 0x0, 0x0, 0xc42044d200, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4201089a0, 0xc42044d200, 0xc42044d200, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc42041f500)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:1180 +0xe1
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:258 +0xbf1

goroutine 19 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.loopyWriter(0x112f3e0, 0xc4205fbc40, 0xc42044c810, 0xc420064fb8)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/transport.go:741 +0x368
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc42041f500)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:290 +0x5e
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:289 +0xd42

goroutine 20 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*http2Client).keepalive(0xc42041f500)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:1330 +0x137
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:294 +0xdb5

goroutine 21 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc42044d0e0)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:109 +0x182
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:95 +0x3f

goroutine 22 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc420226240)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x14a
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14c

goroutine 23 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420457b00)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:1243 +0x235
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420457b00)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:854 +0x1b5
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).connect
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:845 +0xe1

goroutine 29 [IO wait]:
internal/poll.runtime_pollWait(0x7f68e77c2e30, 0x72, 0xc420066970)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420489998, 0x72, 0xffffffffffffff00, 0x111a740, 0x1899400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420489998, 0xc42052e800, 0x400, 0x400)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420489980, 0xc42052e800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc420489980, 0xc42052e800, 0x400, 0x400, 0x8, 0x8, 0x3f3)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e858, 0xc42052e800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42044d710, 0x7f68e77e3ed0, 0xc42000e858, 0x5, 0xc42000e858, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc42044e380, 0x1097417, 0xc42044e4a0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc42044e380, 0xc4203ec000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc4204a1ce0, 0xc420108e38, 0x9, 0x9, 0x30, 0x28, 0xf83d40)
	/usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1116840, 0xc4204a1ce0, 0xc420108e38, 0x9, 0x9, 0x9, 0xc420066df0, 0x400ece, 0xc420066e9f)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x1116840, 0xc4204a1ce0, 0xc420108e38, 0x9, 0x9, 0x85e574, 0xc4203e2810, 0xc4203e0004)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.readFrameHeader(0xc420108e38, 0x9, 0x9, 0x1116840, 0xc4204a1ce0, 0x0, 0x0, 0xc4203e2810, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/hyperledger/fabric/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc420108e00, 0xc4203e2810, 0xc4203e2800, 0x0, 0x0)
	/go/src/github.com/hyperledger/fabric/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc42054a600)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:1180 +0xe1
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:258 +0xbf1

goroutine 30 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.loopyWriter(0x112f3e0, 0xc420226300, 0xc42044dd70, 0xc420543fb8)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/transport.go:741 +0x368
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc42054a600)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:290 +0x5e
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:289 +0xd42

goroutine 31 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.(*http2Client).keepalive(0xc42054a600)
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:1330 +0x137
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:294 +0xdb5
Chaincode installation on remote org 1/peer1 has Failed
=== ERROR !!! FAILED to execute End-2-End Scenario ===

**Comment by yeasy** [comment]
It seems there's IO wait on generating local chaincode package. what machine config are you using?
Can you switch to some quicker one to test again?
I repeated several times, and all work locally.

**Comment by ng2dev** [comment]
You are right the specs where not sufficient. More RAM and there is no problem indeed.
Sorry for wasting your time ;-(
