### ISSUE TITLE
hyperledger rpc端口问题

### ISSUE THREAD

**Issue by ShelleyZhang** [yeasy/docker-compose-files#129]
## Basic Description
配了一个基于kafka的4节点集群，在执行chaincode invoke时会出现invoke succesfull 状态200，payload "unsuppored operation"，日志中也会发现 simulateProposal() result in chaincode status 500。怀疑是广播用的随机端口不在yaml中。这种端口有办法限定吗？

## Environment
1.3

## How to repeat the problem?
只开起yaml中的端口通信，禁用其他端口

**Comment by yeasy** [comment]
Which yaml file?
There's no random broadcasting port in peer.
