### ISSUE TITLE
 [channel: mychannel1] Rejecting broadcast of config message from 172.26.0.11:35706 because of error: error validating channel creation transaction for new channel 'mychannel1', could not succesfully apply update to template configuration: error authorizing update: error validating ReadSet: existing config does not contain element for [Group]  /Channel/Application/Org2MSP but was in the read set 

### ISSUE THREAD

**Issue by vineethmsrcosmos** [yeasy/docker-compose-files#131]
when i trying to create channel in fabric 2.0 i am getting error

**Comment by yeasy** [comment]
@vineethmsrcosmos fabric 2.0 is not released yet.
But from your logs, guess you were using wrong config.

**Comment by vineethmsrcosmos** [comment]
In the hyperledger fabric offical docementation they give fabric 2.0 samples.
can u told where i did mistake in which config file??

**Comment by vineethmsrcosmos** [comment]
---
Organizations:
- Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: crypto-config/ordererOrganizations/example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('OrdererMSP.member')
    Writers:
      Type: Signature
      Rule: OR('OrdererMSP.member')
    Admins:
      Type: Signature
      Rule: OR('OrdererMSP.admin')
- Name: Org1MSP
  ID: Org1MSP
  MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')
    Writers:
      Type: Signature
      Rule: OR('Org1MSP.admin', 'Org1MSP.client')
    Admins:
      Type: Signature
      Rule: OR('Org1MSP.admin')
    Endorsement:
      Type: Signature
      Rule: OR('Org1MSP.peer')
  AnchorPeers:
  - Host: peer0.org1.example.com
    Port: 7051
- Name: Org2MSP
  ID: Org2MSP
  MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')
    Writers:
      Type: Signature
      Rule: OR('Org2MSP.admin', 'Org2MSP.client')
    Admins:
      Type: Signature
      Rule: OR('Org2MSP.admin')
    Endorsement:
      Type: Signature
      Rule: OR('Org2MSP.peer')
  AnchorPeers:
  - Host: peer0.org2.example.com
    Port: 9051
Capabilities:
  Channel:
    V2_0: true
  Orderer:
    V2_0: true
  Application:
    V2_0: true
Application:
  Organizations: 
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
    Endorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
  Capabilities:
    V2_0: true
Orderer:
  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
    - Host: orderer.example.com
      Port: 7050
      ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
    - Host: orderer2.example.com
      Port: 8050
      ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
      ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
    - Host: orderer3.example.com
      Port: 9050
      ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
      ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
    - Host: orderer4.example.com
      Port: 10050
      ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/server.crt
      ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/server.crt
    - Host: orderer5.example.com
      Port: 11050
      ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/server.crt
      ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/server.crt
  Addresses:
  - orderer.example.com:7050
  - orderer2.example.com:8050
  - orderer3.example.com:9050
  - orderer4.example.com:10050
  - orderer5.example.com:11050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations: 
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    BlockValidation:
      Type: ImplicitMeta
      Rule: ANY Writers
Channel:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities:
    V2_0: true
Profiles:
  TwoOrgsChannel:
    Consortium: SampleConsortium
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V2_0: true
    Application:
      Organizations:
      - Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
        Policies:
          Readers:
            Type: Signature
            Rule: OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')
          Writers:
            Type: Signature
            Rule: OR('Org1MSP.admin', 'Org1MSP.client')
          Admins:
            Type: Signature
            Rule: OR('Org1MSP.admin')
          Endorsement:
            Type: Signature
            Rule: OR('Org1MSP.peer')
        AnchorPeers:
        - Host: peer0.org1.example.com
          Port: 7051
      - Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
        Policies:
          Readers:
            Type: Signature
            Rule: OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')
          Writers:
            Type: Signature
            Rule: OR('Org2MSP.admin', 'Org2MSP.client')
          Admins:
            Type: Signature
            Rule: OR('Org2MSP.admin')
          Endorsement:
            Type: Signature
            Rule: OR('Org2MSP.peer')
        AnchorPeers:
        - Host: peer0.org2.example.com
          Port: 9051
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: MAJORITY Endorsement
        Endorsement:
          Type: ImplicitMeta
          Rule: MAJORITY Endorsement
      Capabilities:
        V2_0: true
  SampleMultiNodeEtcdRaft:
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V2_0: true
    Orderer:
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
        - Host: orderer.example.com
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        - Host: orderer2.example.com
          Port: 8050
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
        - Host: orderer3.example.com
          Port: 9050
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
        - Host: orderer4.example.com
          Port: 10050
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/server.crt
        - Host: orderer5.example.com
          Port: 11050
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/server.crt
      Addresses:
      - orderer.example.com:7050
      - orderer2.example.com:8050
      - orderer3.example.com:9050
      - orderer4.example.com:10050
      - orderer5.example.com:11050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Organizations:
      - Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
          Readers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
          Writers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
          Admins:
            Type: Signature
            Rule: OR('OrdererMSP.admin')
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        BlockValidation:
          Type: ImplicitMeta
          Rule: ANY Writers
      Capabilities:
        V2_0: true
    Application:
      Organizations:
      - Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
          Readers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
          Writers:
            Type: Signature
            Rule: OR('OrdererMSP.member')
          Admins:
            Type: Signature
            Rule: OR('OrdererMSP.admin')
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: MAJORITY Endorsement
        Endorsement:
          Type: ImplicitMeta
          Rule: MAJORITY Endorsement
      Capabilities:
        V2_0: true
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: Org1MSP
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')
            Writers:
              Type: Signature
              Rule: OR('Org1MSP.admin', 'Org1MSP.client')
            Admins:
              Type: Signature
              Rule: OR('Org1MSP.admin')
            Endorsement:
              Type: Signature
              Rule: OR('Org1MSP.peer')
          AnchorPeers:
          - Host: peer0.org1.example.com
            Port: 7051
        - Name: Org2MSP
          ID: Org2MSP
          MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')
            Writers:
              Type: Signature
              Rule: OR('Org2MSP.admin', 'Org2MSP.client')
            Admins:
              Type: Signature
              Rule: OR('Org2MSP.admin')
            Endorsement:
              Type: Signature
              Rule: OR('Org2MSP.peer')
          AnchorPeers:
          - Host: peer0.org2.example.com
            Port: 9051

**Comment by vineethmsrcosmos** [comment]
above one is my configtx file pls check it once
