### ISSUE TITLE
1.4版本好多报错：Error response from daemon: manifest for hyperledger/fabric-nodeenv:1.4.6 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by harryheng** [yeasy/docker-compose-files#134]
Error response from daemon: manifest for hyperledger/fabric-nodeenv:1.4.6 not found: manifest unknown: manifest unknown
Error response from daemon: manifest for hyperledger/fabric-baseos:1.4.6 not found: manifest unknown: manifest unknown

**Comment by yeasy** [comment]
Guess some file locations are changed.
Try 1.4.8, which is the latest version of 1.4 series.
