### ISSUE TITLE
Error response from daemon: manifest for hyperledger/fabric-ca:2.0.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by harryheng** [yeasy/docker-compose-files#136]
Error response from daemon: manifest for hyperledger/fabric-ca:2.0.0 not found: manifest unknown: manifest unknown 这种报错怎么解决？

**Comment by yeasy** [comment]
fabric-ca 2.0 is not released yet, can use 1.4.8 image instead.
