### ISSUE TITLE
Command to Deploy Chaincode Wrong in v1.0

### ISSUE THREAD

**Issue by donaldsbell** [yeasy/docker-compose-files#15]
The directions on https://github.com/yeasy/docker-compose-files/tree/master/hyperledger/1.0 to deploy the sample chain code do not work in the v1.0 images.

It appears that Hyperledger v1.0 has changed the command from 
`peer chaincode deploy` 
to something like 
`peer chaincode install`

I would suggest a fix, but I currently do not know the proper command.

**Comment by yeasy** [comment]
@donaldsbell can u help reverify with the new change?

**Comment by donaldsbell** [comment]
I am on vacation until next week, but will be happy to look at this next week.
