### ISSUE TITLE
cant follow detailed steps until make test_cc_instantiate for hyperledger

### ISSUE THREAD

**Issue by alsolh** [yeasy/docker-compose-files#154]
## Basic Description
getting below error and not able to continue rest of the steps

alsolh@alsolh-laptop:~/hyperledger-compose/docker-compose-files/hyperledger_fabric/v2.5.0$ make test_cc_instantiate
Instantiate chaincode on the fabric network
=== Instantiating chaincode on channel businesschannel... ===
=== chaincodeInstantiate for channel businesschannel on org 1/peer 0 ====
cc_name=exp02, version=1.0, args={"Args":["init","a","100","b","200"]}, collection_config=, policy=OR ('Org1MSP.member','Org2MSP.member')
[001 10-27 16:43:55.32 UTC] [chaincodeCmd] checkChaincodeCmdParams -> INFO Using default escc
[002 10-27 16:43:55.33 UTC] [chaincodeCmd] checkChaincodeCmdParams -> INFO Using default vscc
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg Channel 'businesschannel' has been migrated to the new lifecycle, LSCC is now read-only
ChaincodeInstantiation on org 1/peer0 in channel businesschannel failed
=== ERROR !!! FAILED to execute End-2-End Scenario ===
make: *** [Makefile:186: test_cc_instantiate] Error 1

## Environment
v2.5.0 or v2.4.0

## How to repeat the problem?
follow the detailed steps in https://github.com/yeasy/docker-compose-files/blob/master/hyperledger_fabric/docs/steps.md until reaching "make test_cc_instantiate"

## What solutions have u tried?
tried v2.5.0 and v2.4.0, same error happening in both.

## Other Information
the end to end scenario doesnt throw error

**Comment by yeasy** [comment]
The doc seems out dated.
Follow this guideline: https://github.com/yeasy/docker-compose-files/tree/master/hyperledger_fabric#getting-started.
