### ISSUE TITLE
New Keyword version [example: -v 1.0 ] arrived in latest fabric 1.0

### ISSUE THREAD

**Issue by rezwan** [yeasy/docker-compose-files#20]
Hi Yeasy,
1. Currently I can run GRPC for sfhackfest22017/fabric-peer:x86_64-0.7.0-snapshot-c7b3fe0. Is there any node SDK available which supports install,instantiate and version 
2. Is there any documentation or link from where I can get the purpose of version and how new version [v 2.0] chaincode access oldversion [v 1.0] chaincode data.

In CLI we use it like----- fabric# peer chaincode  install -**v 1.0** -n test_cc -p .....

**Comment by yeasy** [comment]
I guess not, and pls ask such question at https://chat.hyperledger.org/channel/fabric-sdk-node.
thanks!
