### ISSUE TITLE
Question/suggestion: Membership Releted Operation instruction in Readme.md file would be great

### ISSUE THREAD

**Issue by rezwan** [yeasy/docker-compose-files#22]
The readme.md instruction is very clear. It works perfectly with me. No issue.
It would be great if I find something there--- related to 
 -member,organization when creating new channel.
 -create/join channel for a peer
 -more about policy
 -Does cli container works with this fabric ca
 - is there any CLI command for creating new member with role. 
Actually hard to find proper doc :)

**Comment by yeasy** [comment]
Thanks for the suggestion, will improve later :)
