### ISSUE TITLE
A function error occurred when I deploy chaincode through node-sdk

### ISSUE THREAD

**Issue by cookedsteak** [yeasy/docker-compose-files#24]
Hi yeasy, I am using fabric v 1.0  and setup fabric-peer, fabric-ca, fabric-orderer in docker container. When I use fabric-sdk-node to deploy the chaincode , there appears an Error message
"[2017-03-16 14:48:55.617] [ERROR] DEPLOY - TypeError: chain.sendInstantiateProposal is not a function  at /mypath/fabric-sdk-node/deploy.js:79:16".
Is this a bug ? Or I missed some steps in previous preparation? :-D

**Comment by yeasy** [comment]
hope this can help u: http://hyperledger-fabric.readthedocs.io/en/latest/asset_setup.html
