### ISSUE TITLE
rpc error: code = 2 desc = Identity or token does not match

### ISSUE THREAD

**Issue by raderio** [yeasy/docker-compose-files#27]
After running
```
docker pull yeasy/hyperledger-fabric:0.6-dp \
  && docker pull yeasy/hyperledger-fabric-peer:0.6-dp \
  && docker pull yeasy/hyperledger-fabric-base:0.6-dp \
  && docker pull yeasy/blockchain-explorer:latest \
  && docker tag yeasy/hyperledger-fabric-peer:0.6-dp hyperledger/fabric-peer \
  && docker tag yeasy/hyperledger-fabric-base:0.6-dp hyperledger/fabric-baseimage \
  && docker tag yeasy/hyperledger-fabric:0.6-dp hyperledger/fabric-membersrvc

docker-compose -f 4-peers-with-membersrvc-explorer.yml up
```

I am trying to registrar
```
curl -X POST --header "Accept: application/json" "http://localhost:7050/registrar" -d'
{
  "enrollId": "test_vp0",
  "enrollSecret": "MwYpmSRjupbT"
}'
```

and I am getting

> vp0_1 | 19:44:48.855 [rest] Register -> INFO 02c REST client login...
> vp0_1 | 19:44:48.856 [rest] Register -> INFO 02d Local data store for client loginToken: /var/hyperledger/production/client/
> vp0_1 | 19:44:48.856 [rest] Register -> INFO 02e Logging in user 'test_vp0' on REST interface...
> vp0_1 | 19:44:48.856 [crypto] RegisterClient -> INFO 02f Registering client [test_vp0] with name [test_vp0]...
> vp0_1 | 19:44:48.866 [crypto] Errorf -> ERRO 030 [client.test_vp0] Failed invoking CreateCertficatePair [rpc error: code = 2 desc = Identity or token does not match.].
> vp0_1 | 19:44:48.866 [crypto] Errorf -> ERRO 031 [client.test_vp0] Failed getting enrollment certificate [id=test_vp0]: [rpc error: code = 2 desc = Identity or token does not match.]
> vp0_1 | 19:44:48.866 [crypto] Errorf -> ERRO 032 [client.test_vp0] Failed retrieving enrollment data [rpc error: code = 2 desc = Identity or token does not match.].
> vp0_1 | 19:44:48.866 [crypto] Errorf -> ERRO 033 [client.test_vp0] Failed registering node crypto engine [rpc error: code = 2 desc = Identity or token does not match.].
> vp0_1 | 19:44:48.867 [crypto] Errorf -> ERRO 034 [client.test_vp0] Failed registering client [test_vp0]: [rpc error: code = 2 desc = Identity or token does not match.]
> vp0_1 | 19:44:48.867 [crypto] RegisterClient -> ERRO 035 Failed registering client [test_vp0] with name [test_vp0] [rpc error: code = 2 desc = Identity or token does not match.].
> vp0_1 | 19:44:48.867 [rest] Register -> ERRO 036 Error on client login: rpc error: code = 2 desc = Identity or token does not match.

**Comment by yeasy** [comment]
0.6 will be not maintained soon.
suggest u migrate to 1.0
