### ISSUE TITLE
Error: Error getting broadcast client: Error connecting to orderer:7050 due to grpc: timed out when dialing

### ISSUE THREAD

**Issue by qnimate** [yeasy/docker-compose-files#30]
I am getting this error:

`Error: Error getting broadcast client: Error connecting to orderer:7050 due to grpc: timed out when dialing`

when running this command:

`peer chaincode  instantiate -v 1.0 -n test_cc -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Args":["init","a","100","b","200"]}' -o orderer:7050`

**Comment by qnimate** [comment]
Replacing `orderer:7050` with `localhost:7050`resolved this issue

**Comment by d8bhatta** [comment]
I have replaced orderer:7050 with localhost:7050 but this doesn't solve my issue.

**Comment by qiang0723** [comment]
It's should be `orderer:7050`, @d8bhatta  Which part and what's error did you meet.

**Comment by d8bhatta** [comment]
@qiang0723  Thank you for your reply. Here is command and error:

build/bin/peer chaincode  instantiate  -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}' -o 0.0.0.0:7050
Error: Error getting endorser client chaincode: PEER_CONNECTIONERROR - Error trying to connect to local peer: grpc: timed out when dialing
Usage:
  peer chaincode instantiate [flags]

**Comment by qiang0723** [comment]
It looks like start orderer service fail.
You can check the logs with `docker logs fabric-orderer0`, and try with `-o orderer0:7050` later.

Ps: I just test success with images `yeasy/hyperledger-fabric-*`, tag 0.8.9 and do as [options]  (https://github.com/yeasy/docker-compose-files/tree/master/hyperledger/1.0) use default channel
