### ISSUE TITLE
Error: Error endorsing query: rpc error: code = 2 desc = Failed to deserialize creator identity, err MSP DEFAULT is unknown

### ISSUE THREAD

**Issue by qnimate** [yeasy/docker-compose-files#32]
I am getting this error when running invoke and query commands. The chaincode got deployed successfully and I can see the docker container.

`Error: Error endorsing query: rpc error: code = 2 desc = Failed to deserialize creator identity, err MSP DEFAULT is unknown`

**Comment by qiang0723** [comment]
May be you can add `- ORDERER_GENERAL_LOCALMSPID=DEFAULT`  in  docker-compose.ymal , Does this ID  Corresponds to the ID of the file `common/configtx/tool/configtx.yaml` ?  I'm not sure.

**Comment by yeasy** [comment]
Please try the latest image.

**Comment by qnimate** [comment]
![screen shot 2017-04-06 at 3 59 14 pm](https://cloud.githubusercontent.com/assets/7037606/24753155/09866408-1ae2-11e7-9dfb-f76365567bec.png)

I have the latest image. I am using hyperledger/fabric-peer image to create peer container.

**Comment by yeasy** [comment]
Fixed in latest images.
