### ISSUE TITLE
Error while querying

### ISSUE THREAD

**Issue by qnimate** [yeasy/docker-compose-files#33]
This is the error in peer node logs:

`fabric-peer0 | 2017-04-07 14:48:53.145 UTC [lccc] Invoke -> ERRO 03e ChaincodeId: test_cc does not exist on channel: testchainid(err:chaincode not found test_cc)`

And this is the error of the query transaction:

`Error: Error endorsing query: rpc error: code = 2 desc = failed to obtain cds for test_cc - transaction not found test_cc/testchainid`

**Comment by yeasy** [comment]
Pls use the issue template.
