### ISSUE TITLE
Error while querying and invoking

### ISSUE THREAD

**Issue by qnimate** [yeasy/docker-compose-files#34]
## Environment
Ubuntu OS and Docker version 17.04.0-ce, build 4845c56

## How to repeat the problem?
Run `docker-compose run` and then on the default channel install and instantiate runs fine. At the time of query and invoke getting `Error: Error endorsing query: rpc error: code = 2 desc = failed to obtain cds for test_cc - transaction not found test_cc/testchainid` and in the peer logs I see this error `fabric-peer0 | 2017-04-09 05:46:54.530 UTC [lccc] Invoke -> ERRO b5b ChaincodeId: test_cc does not exist on channel: testchainid(err:chaincode not found test_cc)`

## What solutions have u tried?
Haven't tried any solutions yet.

## Other Information
I can see the docker container `dev-peer0-test_cc-1.0` running.

**Comment by qiang0723** [comment]
Now you can follow the manual[https://github.com/yeasy/docker-compose-files/tree/master/hyperledger/1.0#test-chaincode-with-new-created-channel-optional], this part can be work.

**Comment by qnimate** [comment]
@qiang0723 Thanks. It works with custom channel not in default channel. But that's fine.

**Comment by qiang0723** [comment]
You can try change `orderer0` to `ordere`r in docker-compose.ymal. then it can support default testchainid.

**Comment by qiang0723** [comment]
We have updated the REDME, And support chaincode operation in default channel testchainid now. please try it. Thanks!

**Comment by qiang0723** [comment]
We have updated the REDME, And support chaincode operation in default channel testchainid now. please try it. Thanks!

**Comment by yeasy** [comment]
Fixed.
