### ISSUE TITLE
How to send an query or invoke transaction from Node.js

### ISSUE THREAD

**Issue by qnimate** [yeasy/docker-compose-files#39]
I am able to query and invoke transactions from CLI.

I want to make a query and invoke from node.js using https://github.com/hyperledger/fabric-sdk-node/tree/master/fabric-ca-client

Can you provide an simple example? In the example of the fabric-sdk-node they have cert files. What's the need of those. Cert files are already in the docker container and I just want to make an transaction.

**Comment by yeasy** [comment]
maybe this can help: https://hyperledger-fabric.readthedocs.io/en/latest/getting_started.html
