### ISSUE TITLE
How can I set up hyperledger fabric with multiple hosts using Docker?

### ISSUE THREAD

**Issue by yonchin** [yeasy/docker-compose-files#40]
## Environment
Any environment information, e.g., os, tool versions, image version.

## How to repeat the problem?
Detailed steps to repeat the problem. 

## What solutions have u tried?
Potential solutions you have tried, e.g., search Google or restart the computer.

## Other Information
Other information u think can help to fix the problem.

**Comment by yeasy** [comment]
FYI. https://github.com/yeasy/blockchain_guide/blob/master/fabric/v0.6/install.md
