### ISSUE TITLE
How can I set up hyperledger fabric 1.0 (not 0.6)  with multiple hosts using Docker ?

### ISSUE THREAD

**Issue by yonchin** [yeasy/docker-compose-files#41]

**Comment by jamesv84** [comment]
I am also interested in this. In particular, I would like to use the existing HL 1.0 docker compose files to install on Host A (which I have already done), and then run something else on Host B to install peers there and connect the peers from Host B to the peers on Host A (where I initially installed HL 1.0).

**Comment by yeasy** [comment]
IMHO, there are 2 options:
* Manually setup and startup
* Use CoE to help distribute and connect

**Comment by RashitKhamidullin** [comment]
Hi, @jamesv84 . Have you built a network over two physical hosts?

**Comment by wahabjawed** [comment]
Check out this guide using Fabric 1.0
https://medium.com/@wahabjawed/hyperledger-fabric-on-multiple-hosts-a33b08ef24f
