### ISSUE TITLE
Error creating configtx manager: Disallowed channel group: Consortiums

### ISSUE THREAD

**Issue by holzeis** [yeasy/docker-compose-files#42]
## Environment
macOS Sierra 10.12.3

## How to repeat the problem?
I've successfully run the first part of the instructions. When trying to test chaincode with a new created channel ...

`docker-compose -f docker-compose-new-channel.yml up`

I get the following error ...

`fabric-orderer0 | 2017-05-06 20:51:21.257 UTC [orderer/multichain] newLedgerResources -> CRIT 001 Error creating configtx manager and handlers: Error creating group Consortiums: Disallowed channel group: Consortiums`

I've also called docker-compose down before starting anew. It seams this is necessary as I've got a lot of other errors otherwise.

**Comment by yeasy** [comment]
Seems u're using the old image version.

Could u try with the latest one?
