### ISSUE TITLE
Instantiate chaincode error

### ISSUE THREAD

**Issue by myqq0000** [yeasy/docker-compose-files#48]
## Environment
Mac OS 10.12.5
Docker 17.03
Go 1.8
Hyperledger Fabric x86_64-1.0.0 alpha

## How to repeat the problem?
I try the 'docker-compose-dev.yaml' today.
And I get 4 containers:
- fabric-cli
- fabric-peer0
- fabric-order0
- fabric-ca
And then I try to deploy my chaincode. I install my chaincode successfully. But then I try to instantiate it. There comes some erros:
`fabric-peer0 | FROM hyperledger/fabric-baseos:x86_64-0.3.0
fabric-peer0 | ADD binpackage.tar /usr/local/bin
fabric-peer0 | LABEL org.hyperledger.fabric.chaincode.id.name="test_cc" \
fabric-peer0 |       org.hyperledger.fabric.chaincode.id.version="1.0" \
fabric-peer0 |       org.hyperledger.fabric.chaincode.type="GOLANG" \
fabric-peer0 |       org.hyperledger.fabric.version="1.0.0-preview" \
fabric-peer0 |       org.hyperledger.fabric.base.version="0.3.0"
fabric-peer0 | ENV CORE_CHAINCODE_BUILDLEVEL=1.0.0-preview
fabric-peer0 | 2017-05-24 14:21:58.167 UTC [util] DockerBuild -> DEBU 48d Attempting build with image hyperledger/fabric-ccenv:x86_64-1.0.0-preview
fabric-peer0 | 2017-05-24 14:21:58.168 UTC [util] DockerBuild -> DEBU 48e Image hyperledger/fabric-ccenv:x86_64-1.0.0-preview does not exist locally, attempt pull
fabric-peer0 | 2017-05-24 14:22:10.093 UTC [chaincode-platform] func1 -> ERRO 48f Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:x86_64-1.0.0-preview: API error (404): {"message":"manifest for hyperledger/fabric-ccenv:x86_64-1.0.0-preview not found"}
fabric-peer0 | 2017-05-24 14:22:10.094 UTC [dockercontroller] deployImage -> ERRO 490 Error building images: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:x86_64-1.0.0-preview: API error (404): {"message":"manifest for hyperledger/fabric-ccenv:x86_64-1.0.0-preview not found"}
fabric-peer0 | 2017-05-24 14:22:10.094 UTC [dockercontroller] deployImage -> ERRO 491 Image Output:
fabric-peer0 | ********************
fabric-peer0 |
fabric-peer0 | ********************`

I thinks it beacuse of its fabric version is 1.0.0-preview, but my fabric version is 1.0.0-alpha.
But I don't know how to edit it? Thanks a lot!

## What solutions have u tried?
I have searched the keyword '1.0.0-preview' in this repository, but there is only a scripts for download images, I change it but it's still error...

Thanks a lot!! :)

**Comment by qiang0723** [comment]
From the error log, seems lack images `hyperledger/fabric-ccenv:x86_64-1.0.0-preview`, suggest running `download_images.sh` first.

**Comment by myqq0000** [comment]
@qiang0723 I pull the images of hyperledger-fabric-1.0.0-alpha at first.
The images which I pulled are in this picture:

And then I use the command `docker-compose -f docker-compose-dev.yml up` to start the dev containers.
Then I can create channel and join it. And I can install chaincode, too.
But when I try to instantiate it, it comes errors.

And I try your advice just now.
I use the command `bash scripts/download_images.sh` at first.
And then I get some new images like these:


But when I try to start the dev containers again.
Some errors happen.

`➜  1.0 git:(master) ✗ docker-compose -f docker-compose-dev.yml up
fabric-ca is up-to-date
fabric-orderer0 is up-to-date
fabric-peer0 is up-to-date
Starting fabric-cli

ERROR: for cli  Cannot start service cli: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/go/src/github.com/hyperledger/fabric\") set in config.json failed: no such file or directory"
ERROR: Encountered errors while bringing up the project.`

Emmm... I don't know what happened. Maybe because of new images which I downloaded just now?

Thanks a lot!! :)

**Comment by qiang0723** [comment]
Your previous operation mixes office images and the operation we provide, obviously wrong.  
Although the images we provide is the same as official, still has some different in structure, so if you want to setup up fabric in our way, you must use images we provided.

Second question:
Did you git clone fabric from [official] (https://github.com/hyperledger/fabric)? and put it in 
` $GOPATH/src/github.com/hyperledger/`
This error is because you didn't set env `$GOPATH` or this env doesn't take effort, or this directory doesn't exist.
suggest set env `export $GOPATH=/go`  and git clone code.

**Comment by yeasy** [comment]
@myqq0000 First, pls clean ur env by removing all existing docker images, then use the [download_images.sh](https://github.com/yeasy/docker-compose-files/blob/master/hyperledger/1.0/scripts/download_images.sh) to download necessary images.

**Comment by myqq0000** [comment]
@yeasy @qiang0723 
Emmm... I remove all images of hyperledger just now.
But there are still the same errors...

> root@cli:/go/src/github.com/hyperledger/fabric# peer chaincode instantiate -v 1.0 -n test_cc -c '{"Args":["init","a","100","b","200"]}' -o orderer0:7050
> 2017-05-25 09:11:42.948 UTC [msp] getMspConfig -> INFO 001 intermediate certs folder not found at [/etc/hyperledger/fabric/msp/intermediatecerts]. Skipping.: [stat /etc/hyperledger/fabric/msp/intermediatecerts: no such file or directory]
> 2017-05-25 09:11:42.948 UTC [msp] getMspConfig -> INFO 002 crls folder not found at [/etc/hyperledger/fabric/msp/intermediatecerts]. Skipping.: [stat /etc/hyperledger/fabric/msp/crls: no such file or directory]
> 2017-05-25 09:11:42.967 UTC [msp] GetLocalMSP -> DEBU 003 Returning existing local MSP
> 2017-05-25 09:11:42.967 UTC [msp] GetDefaultSigningIdentity -> DEBU 004 Obtaining default signing identity
> 2017-05-25 09:11:42.968 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 005 Using default escc
> 2017-05-25 09:11:42.969 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 006 Using default vscc
> 2017-05-25 09:11:42.969 UTC [msp/identity] Sign -> DEBU 007 Sign: plaintext: 0AB1080A6908031A0C08CEBF9AC90510...30300A000A04657363630A0476736363
> 2017-05-25 09:11:42.969 UTC [msp/identity] Sign -> DEBU 008 Sign: digest: 103432FEC525EEE7F4621BD95E37789FBF7928D9CDFB85A9D012D2D26F4EF338
> Error: Error endorsing chaincode: rpc error: code = 2 desc = Error starting container: Failed to generate platform-specific docker build: Error creating container: no such image
> Usage:
>   peer chaincode instantiate [flags]
> 
> Global Flags:
>       --cafile string              Path to file containing PEM-encoded trusted certificate(s) for the ordering endpoint
>   -C, --chainID string             The chain on which this command should be executed (default "testchainid")
>   -c, --ctor string                Constructor message for the chaincode in JSON format (default "{}")
>   -E, --escc string                The name of the endorsement system chaincode to be used for this chaincode
>   -l, --lang string                Language the chaincode is written in (default "golang")
>       --logging-level string       Default logging level and overrides, see core.yaml for full syntax
>   -n, --name string                Name of the chaincode
>   -o, --orderer string             Ordering service endpoint
>   -p, --path string                Path to chaincode
>   -P, --policy string              The endorsement policy associated to this chaincode
>       --test.coverprofile string   Done (default "coverage.cov")
>   -t, --tid string                 Name of a custom ID generation algorithm (hashing and decoding) e.g. sha256base64
>       --tls                        Use TLS when communicating with the orderer endpoint
>   -u, --username string            Username for chaincode operations when security is enabled
>   -v, --version string             Version of the chaincode specified in install/instantiate/upgrade commands
>   -V, --vscc string                The name of the verification system chaincode to be used for this chaincode

These are my images:

> REPOSITORY                         TAG                  IMAGE ID            CREATED             SIZE
> hyperledger/fabric-peer            latest               885dc22631be        3 days ago          944 MB
> yeasy/hyperledger-fabric-peer      0.9.3                885dc22631be        3 days ago          944 MB
> hyperledger/fabric-ca              latest               10da547accd0        3 days ago          849 MB
> yeasy/hyperledger-fabric-ca        0.9.3                10da547accd0        3 days ago          849 MB
> hyperledger/fabric-orderer         latest               06ae616c02b5        3 days ago          937 MB
> yeasy/hyperledger-fabric-orderer   0.9.3                06ae616c02b5        3 days ago          937 MB
> hyperledger/fabric-baseos          x86_64-1.0.0-alpha   3a66c7c635f0        3 days ago          905 MB
> hyperledger/fabric-ccenv           x86_64-1.0.0-alpha   3a66c7c635f0        3 days ago          905 MB
> yeasy/hyperledger-fabric-base      0.9.3                3a66c7c635f0        3 days ago          905 MB

And these are my containers:

> CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                             NAMES
> fc5feea61a8b        hyperledger/fabric-peer      "bash -c 'while tr..."   11 minutes ago      Up 11 minutes       7050-7059/tcp                                     fabric-cli
> 6480a4b88b62        hyperledger/fabric-peer      "peer node start -..."   11 minutes ago      Up 11 minutes       7050/tcp, 7052-7059/tcp, 0.0.0.0:7051->7051/tcp   fabric-peer0
> 4509ca781d49        hyperledger/fabric-ca        "fabric-ca-server ..."   11 minutes ago      Up 11 minutes       7054/tcp, 0.0.0.0:8888->8888/tcp                  fabric-ca
> af548164b9d7        hyperledger/fabric-orderer   "orderer"                11 minutes ago      Up 11 minutes       0.0.0.0:7050->7050/tcp                            fabric-orderer0

I think maybe it can't solve... Maybe I need to download fabric-1.0.0-preview to have a try?

**Comment by qiang0723** [comment]
Actually just need two steps to start a fabric network, no more extra steps or images.
1. bash download_images.sh
2.sudo docker-compose up

**Comment by myqq0000** [comment]
Uh... I try it again. Remove all images in my docker. And run the command `bash download_images.sh` to download images.
And then I get some images like these:
![image](https://cloud.githubusercontent.com/assets/19700709/26495280/9e6dce9a-4255-11e7-9bb0-9f45cfacdf10.png)

And in order to prevent the second question which I mentioned previously, I remove the directory of 'fabric', and git clone it again.
But when I run the command `peer chaincode instantiate -v 1.0 -n test_cc -c '{"Args":["init","a","100","b","200"]}' -o orderer0:7050`
![image](https://cloud.githubusercontent.com/assets/19700709/26495492/69dd3674-4256-11e7-80ee-8c3d33bbe0c4.png)

It get errors again. And the errors are same...

I don't know why and I can't solve it with myself.
So I maybe try some else way to run a development environment...
Thank you all the way~ :)

(By the way, could you give me some tutorials about how to run a dev-environment? I want to debug my chaincode but I don't know how to start a dev-environment... I read it in some docs, but there's no tutorial about how to set up it... Thanks a lot!!)

**Comment by yeasy** [comment]
@myqq0000 No you were not following the script.

In the script, that cannot be any images with the alpha tag, pls do clean all existing images and use the provided latest download_images.sh script. The generated image should look like (now 0.9.3 is the newer one)

hyperledger/fabric-orderer            latest                                 d69ce2b6429f        2 weeks ago         935 MB
yeasy/hyperledger-fabric-orderer      0.9.2                                  d69ce2b6429f        2 weeks ago         935 MB
hyperledger/fabric-peer               latest                                 43e194fff3e7        2 weeks ago         943 MB
yeasy/hyperledger-fabric-peer         0.9.2                                  43e194fff3e7        2 weeks ago         943 MB
hyperledger/fabric-ca                 latest                                 42568aea8465        2 weeks ago         847 MB
yeasy/hyperledger-fabric-ca           0.9.2                                  42568aea8465        2 weeks ago         847 MB
hyperledger/fabric-ccenv              x86_64-1.0.0-preview                   3d90ccb29493        2 weeks ago         903 MB
yeasy/hyperledger-fabric-base         0.9.2                                  3d90ccb29493        2 weeks ago         903 MB
hyperledger/fabric-baseimage          latest                                 3d90ccb29493        2 weeks ago         903 MB
hyperledger/fabric-baseos             x86_64-1.0.0-preview                   3d90ccb29493        2 weeks ago         903 MB

**Comment by myqq0000** [comment]
@yeasy Thanks a lot!!
I delete all images in my docker and run the script again.
And then it download the 1.0.0-preview...

But if I only delete the two 1.0.0-alpha images and run this script, it will still download a 1.0.0-alpha for me...
I don't know why.

Anyway, thanks a lot!! 
谢谢大佬辛苦了！:)

**Comment by figago84** [comment]
Hi myqq0000, could you solve your problem?? I have the same problem and I cannot solve it. Please, any help will be appreciated.
