### ISSUE TITLE
hyperledger docker-compose.yml for fabric-peer0 invalid command

### ISSUE THREAD

**Issue by Aquariuslt** [yeasy/docker-compose-files#49]
## Environment
OS: Win7 x64 && Ubuntu 17.04
GO: Win7 1.8 && Ubuntu 17.04

## How to repeat the problem?
Following [https://yeasy.gitbooks.io/blockchain_guide/content/hyperledger/1.0.html](https://yeasy.gitbooks.io/blockchain_guide/content/hyperledger/1.0.html)
 
Setting up docker images and trying demo.

In step [https://yeasy.gitbooks.io/blockchain_guide/content/hyperledger/1.0.html#启动-fabric-10-网络](https://yeasy.gitbooks.io/blockchain_guide/content/hyperledger/1.0.html#启动-fabric-10-网络)

`docker-compose up`

peer docker instance will exit by `invalid flags for commond peer`

## What solutions have u tried?
After update 
[https://github.com/yeasy/docker-compose-files/blob/master/hyperledger/1.0/docker-compose.yml](https://github.com/yeasy/docker-compose-files/blob/master/hyperledger/1.0/docker-compose.yml)

line 55, removing -o:

```
command: peer node start orderer0:7050
```

it works normally.

**Comment by qiang0723** [comment]
Which images version did you pull? 0.8.4 or 0.9.3?
we change the command `peer node start` to `peer node start -o orderer0:7050` from version0.9.0
we will keep updating in this project and https://github.com/yeasy/blockchain_guide/blob/master/fabric/1.0.md

**Comment by Aquariuslt** [comment]
@qiang0723 
I follow [https://yeasy.gitbooks.io/blockchain_guide/content/hyperledger/1.0.html#获取-docker-镜像](https://yeasy.gitbooks.io/blockchain_guide/content/hyperledger/1.0.html#获取-docker-镜像)

and download version 0.8.4.

And I have try pulling 0.9.3 and following
[https://github.com/yeasy/blockchain_guide/blob/master/fabric/1.0.md](https://github.com/yeasy/blockchain_guide/blob/master/fabric/1.0.md)

Now it seems pass.
Thanks for your reply.

(Please remind update gitbook repository document :) )
