### ISSUE TITLE
Path to Docker-compose.yml in start_fabric.sh

### ISSUE THREAD

**Issue by tpasquet** [yeasy/docker-compose-files#50]
I found two small issues : 
1) In the Readme, setup_fabric.sh is no longer available, should be rename for start_fabric.sh ?
2) When executing start_fabric.sh, the docker-compose.yml is not found automatically : 
--> "ERROR: .IOError: [Errno 2] No such file or directory: u'./docker-compose.yml'"

Thanks for your work btw !

**Comment by yeasy** [comment]
Thanks for the report, i've update the instructions.
is it working for u now?
