### ISSUE TITLE
docker-compose -f 4-peers-with-membersrvc-explorer.yml up

### ISSUE THREAD

**Issue by blueskylxb** [yeasy/docker-compose-files#57]
when exec docker-compose -f 4-peers-with-membersrvc-explorer.yml up, happen 
ERROR: for membersrvc0  Cannot create container for service membersrvc0: mkdir /var/lib/docker/overlay/e1e5b9ad4a801fe82ce5b9f32fdff4e1a0c06d9f3cfdd9b7691b5103c5db5f73-init/merged/dev/shm: invalid argument
ERROR: Encountered errors while bringing up the project.

**Comment by yeasy** [comment]
pls use the given template to provide the env info.

**Comment by blueskylxb** [comment]
Sorry, I can not understand your answer. Can you show me detail. Thanks.

**Comment by yeasy** [comment]
Pls use the default template provided at https://github.com/yeasy/docker-compose-files/issues/new.
