### ISSUE TITLE
where to view the chaincode log

### ISSUE THREAD

**Issue by yqbjtu** [yeasy/docker-compose-files#6]
I write some chaincode and deploy it . but there is some results, which is not my expected. I  add some log to chiancode as debug info like "fmt.Println("id:" + args[0] + " - state" + args[1])", after I enter into the docker by "docker exec -it xxxx  bash", then can't find where the chaincode log is.

Thank you!

**Comment by yeasy** [comment]
see through the docker-compose start cli.
or use `docker-compose logs -f` where the docker-compose.yml stays.

**Comment by yqbjtu** [comment]
Thank you!  "docker-compose logs" show the logs.

I use 
var logger = shim.NewLogger("BienChaincode")
func main() {
        logger.SetLevel(shim.LogInfo)
	err := shim.Start(new(BienChaincode))
	if err != nil {
		fmt.Printf("Error starting BienChaincode chaincode: %s", err)
	}
}

then call   logger.Infof("init logger arg0=%s", args[0])

when I used the 
peer chaincode deploy -p ./ -c '{"Function":"init", "Args": ["hi there2"]}' -u  jim

to deploy the chaincode, in the container interal, it seem that "docker-compose logs" can't show the log.

**Comment by yeasy** [comment]
yes, in that case, you should find your chaincode container id by `docker ps`, then use

```
docker logs -f chaincode_container_id
```

**Comment by yqbjtu** [comment]
Thank you very much! I get the logs
