### ISSUE TITLE
grpc: addrConn.resetTransport failed to create client transport: connection error:  desc = "transport: failed to write window update: write tcp 172.18.0.5:49656->172.18.0.4:7051:  write: broken pipe"; Reconnecting to {peer0.org1.example.com:7051 <nil>}   transport: http2Client.notify Error got notified that the client transport was broken read tcp 172.18.0.5:49658->172.18.0.4:7051:  read: connection reset by peer.

### ISSUE THREAD

**Issue by smfaizalkhan** [yeasy/docker-compose-files#60]
## Environment
 Ubuntu,Docker

## How to repeat the problem?
Followed the steps to create an Orderer,Peer  
using the docker-compose-1peer.yaml,so all the ertificates are mounted on to the conatiner
Then executed docker exec -it fabric-cli bash command to enter CLI and then entered peer channel list command to check the channels .Thenf aced the above error

## What solutions have u tried?
Docker has started the conatiners with 
  -- Orderer with ip 172.18.0.3
  -- Peer with  ip      172.18.0.4
  -- CLI with  ip      172.18.0.5

When peer channel list is executed it tries to connect with peer from CLI and at that point the issue occurs

Tried pining peer 172.18.0.4 and telneted successfully ,But with CLI it was not succesful.
## Other Information
Other information u think can help to fix the problem.

The write broken error occurs if the connection is not successful  and some wrtie job is done on that connection.but in this case ping to the peer is succesful,So let me knwo what actually is the issue

**Comment by qiang0723** [comment]
@smfaizalkhan, I think the peer node didn't start successfully. 
whether the peer occurs some error logs (docker logs peer0.org1.example.com) and how did you start the network?

**Comment by smfaizalkhan** [comment]
[peer0.org1.example.com logs.zip](https://github.com/yeasy/docker-compose-files/files/1073621/peer0.org1.example.com.logs.zip)

@qiang0723  :Please find the logs for the container  peer0.org1.example.com

**Comment by qiang0723** [comment]
Apologies!, it is difficult to locate your cause of the error from the logs. please use `docker-compose-2orgs-4peers.yaml` first, refer to [Bootup and test Fabric 1.0](https://github.com/yeasy/docker-compose-files/tree/master/hyperledger/1.0#bootup-and-test-fabric-10) and I will test/modify docker-compose-1peers.yaml now. 
Notice: we support TLS now, if you don't want to use it, you can setting *_TLS_ENABLED=false in docker-compose-2orgs-4peers.yaml, peer-base.yaml and orderer-base.yaml.

**Comment by smfaizalkhan** [comment]
No issues ,Thanks for the feedback.In the meant time while following up with docker-compose-2orgs-4peers.yaml first, refer to Bootup and test Fabric 1.0 ,i noticed that while initializing fabric and executing the command  $ bash ./scripts/initialize.sh  after docker-exec -it fabric-cli bash it sayd no cuch folder or directory .It is a mounting issue .If so i dont find the file

**Comment by qiang0723** [comment]
There may have path problem before, but now we have fixed it.

**Comment by smfaizalkhan** [comment]
Sorry I got it.When i cloned it,  the file "initialzie.sh" was missing which has been added 5 days back,But now i get 
"Error: Invalid channel create transaction : mismatched channel ID mychannel != businesschannel" error 
The content of log.txt is as below

cat log.txt
2017-06-14 07:21:50.908 UTC [msp] getMspConfig -> INFO 001 intermediate certs folder not found at [/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/intermediatecerts]. Skipping.: [stat /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/intermediatecerts: no such file or directory]
2017-06-14 07:21:50.908 UTC [msp] getMspConfig -> INFO 002 crls folder not found at [/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/intermediatecerts]. Skipping.: [stat /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/crls: no such file or directory]
2017-06-14 07:21:50.908 UTC [msp] getMspConfig -> INFO 003 MSP configuration file not found at [/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/config.yaml]: [stat /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/config.yaml: no such file or directory]
2017-06-14 07:21:50.960 UTC [msp] GetLocalMSP -> DEBU 004 Returning existing local MSP
2017-06-14 07:21:50.960 UTC [msp] GetDefaultSigningIdentity -> DEBU 005 Obtaining default signing identity
2017-06-14 07:21:50.985 UTC [channelCmd] InitCmdFactory -> INFO 006 Endorser and orderer connections initialized
Error: Invalid channel create transaction : mismatched channel ID mychannel != businesschannel

**Comment by qiang0723** [comment]
That's because you didn't update project,  we changed default channel `mychannel` to `businesschannel`, and related configurations have changed also.

**Comment by smfaizalkhan** [comment]
Done ..Downloaded the latest channel.tx artificat and copied into my existing folder and now it is done!!
Thanks

**Comment by smfaizalkhan** [comment]
Yes ,Done ..Downloaded the latest channel.tx artificat and copied into my existing folder and now it is done!!
Now i got  the same Invalid channel create transaction : mismatched channel ID mychannel != businesschannel for Ancor Channel,So i copied a;ll the contents of the channel-artifacts from github and copied into local channel_artificats  and then started the network using "sudo docker-compose -f docker-compose-2orgs-4peers.yaml up" and while running the initialise.sh script from fabric-cli got the BAD_REQUEST as below

 Sign: digest: BF497B88C1DC913F62ADE5638F539CB906FDA5B3F78BD44214C7244B311A6561 
Error: Got unexpected status: BAD_REQUEST

In the orderer i found a warning 

orderer.example.com       | 2017-06-14 08:01:35.901 UTC [orderer/common/broadcast] Handle -> WARN 213 Rejecting CONFIG_UPDATE because: Error authorizing update: Error validating ReadSet: Readset expected key [Groups] /Channel/Application at version 0, but got version 1

From the same issue (51)  @yeasy  has asked for OS version .

I'm using ubuntu 16.04 LTS

**Comment by qiang0723** [comment]
In scripts/initialise.sh and scripts/test-4peers.sh have a env called CHANNEL_NAME, did you change it to businesschannel?

**Comment by qiang0723** [comment]
#51 , later we will complete doc, hope can help you.

**Comment by smfaizalkhan** [comment]
Yes, #51 later 
@qiang : in test-4ppers.sh i have changed it to businesschannel and started the network ,i still get 
"Error: Got unexpected status: BAD_REQUEST"
I check the following files.

1) initialize.sh         (CHANNEL_NAME="$1" : ${CHANNEL_NAME:="businesschannel"}  )
2) channel.json       ( "channel_id": "businesschannel" )
3) test_4peers.sh    (CHANNEL_NAME="$1" : ${CHANNEL_NAME:="businesschannel"} 

Is there anywhere else that i sud change the channel name ?

**Comment by qiang0723** [comment]
suggest use the latest version compare with yours, find differents

**Comment by smfaizalkhan** [comment]
Yes qiang.I will rmi all docker conatiners and images ,Start afresh

**Comment by smfaizalkhan** [comment]
Thanks @qiang0723  :It was successful after doing it afresh.

Channel created and got the  ===== All GOOD initialization completed ============

So i ran the test_4peers.sh,But that time i got the Output as Attempting to Query PEER 2 and then it exists

**Comment by GuillaumeCisco** [comment]
I get this exact same error when I try to execute a `peer` command for querying my chaincode from outside the docker network i.e my own machine.
If I create a docker container from the docker-compose file with the attribute `networks` correctly filled, it works great, but not if I test it from my own machine. How can I tell the peer command to use the same network created by the docker-compose file?
Thank you.
