### ISSUE TITLE
error when i execute "bash setupPbft.sh" 

### ISSUE THREAD

**Issue by yuanyuansiyuan** [yeasy/docker-compose-files#7]
The error information is:Cannot open self /usr/local/bin/docker-compose or archive /usr/local/bin/docker-compose.pkg
Error response from daemon: Get https://registry-1.docker.io/v2/yeasy/hyperledger-fabric/manifests/latest: net/http: TLS handshake timeout
And i always encountered with "tag latest  not found" or TLS timeout error.
My environment is vagrant and the ubuntu virtual machine in it. Can you show me more details about construct the development environment of fabric? Thank you very much for your time and patience!

**Comment by yeasy** [comment]
Yes, this often happens.
Suggest u try building at some virtual machine at clouds, which have better networking connectivity, e.g., AWS.

**Comment by yuanyuansiyuan** [comment]
Thank you for your feedback! I will try on the clouds.
