### ISSUE TITLE
 2017-06-24 08:45:16.049 UTC [main] main -> ERRO 005 Cannot run peer because error when setting up MSP from directory /etc/hyperledger/fabric/msp: err KeyMaterial not found in SigningIdentityInfo orderer.example.com exited with code 1

### ISSUE THREAD

**Issue by smfaizalkhan** [yeasy/docker-compose-files#72]
## Environment
 os :Ubuntu 

## How to repeat the problem?
After Pulling  required Docker images,while executing sudo docker-compose -f docker-compose-2orgs-4peers.yaml up

## What solutions have u tried?
Potential solutions you have tried, e.g., search Google or restart the computer.

## Other Information
Other information u think can help to fix the problem.

**Comment by qiang0723** [comment]
Can you help verify this patchset? Thanks.
 https://github.com/qiang0723/docker-compose-files

**Comment by smfaizalkhan** [comment]
OK .Thanx
