### ISSUE TITLE
fabric-ccenv镜像问题

### ISSUE THREAD

**Issue by lightning-li** [yeasy/docker-compose-files#8]
成功启动一个noops集群后，当部署chaincode的时候，提示deployimage错误，原因是缺少hyperledger/fabric-ccenv:x86_64-基础镜像，奇怪的是x86_64-后并没有接版本号，按照我的理解，版本号是在fabric下的Makefile中确定的，因此make peer的时候应该会将版本号信息接到x86_64-后，不知为何缺少版本号？官方也并没有提供fabric-ccenv的基础镜像，因此主动去pull也不会成功。
我的解决办法是，从vagrant的开发环境中导出了fabric-ccenv的镜像，并将其标签为fabric-ccenv:x86_64-，因此部署chaincode成功。
是我遗漏了什么？还是您提供的解决方案有遗漏？

**Comment by yeasy** [comment]
This is because the latest code changes the required image name.

In that case, you can tag the baseimage to the missing tag.

To keep stable, suggest u use the 0.6 image.
