### ISSUE TITLE
Error response from daemon: No such container: fabric-cli

### ISSUE THREAD

**Issue by jinpeng049** [yeasy/docker-compose-files#88]
when i excute cmd `make init` then have some problems

root@ubuntu:/opt/hyperledger/docker-compose-files-master/hyperledger/1.0# make init
docker exec -it fabric-cli bash ./scripts/initialize.sh
Error response from daemon: No such container: fabric-cli
Makefile:20: recipe for target 'init' failed
make: *** [init] Error 1

when i excute cmd `make start` then have some problems

root@ubuntu:/opt/hyperledger/docker-compose-files-master/hyperledger/1.0# make start 
docker-compose -f "docker-compose-2orgs-4peers.yaml" up -d  # Start a fabric network
Recreating adea231c07c9_adea231c07c9_adea231c07c9_adea231c07c9_peer1.org1.example.com ... 
Recreating a9f99d52ad8e_a9f99d52ad8e_a9f99d52ad8e_a9f99d52ad8e_peer0.org2.example.com ... 
Recreating adea231c07c9_adea231c07c9_adea231c07c9_adea231c07c9_peer1.org1.example.com
Recreating b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_fabric-ca ... 
Recreating a9f99d52ad8e_a9f99d52ad8e_a9f99d52ad8e_a9f99d52ad8e_peer0.org2.example.com
Recreating 4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_orderer.example.com ... 
Recreating b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_fabric-ca
Recreating 443e8a8a63ee_443e8a8a63ee_443e8a8a63ee_443e8a8a63ee_peer1.org2.example.com ... 
Recreating 1c2d29f3db88_1c2d29f3db88_1c2d29f3db88_1c2d29f3db88_peer0.org1.example.com ... 
Recreating 4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_orderer.example.com
Recreating 443e8a8a63ee_443e8a8a63ee_443e8a8a63ee_443e8a8a63ee_peer1.org2.example.com
Recreating adea231c07c9_adea231c07c9_adea231c07c9_adea231c07c9_peer1.org1.example.com ... error

Recreating a9f99d52ad8e_a9f99d52ad8e_a9f99d52ad8e_a9f99d52ad8e_peer0.org2.example.com ... error

Recreating b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_b92efc7a7dc0_fabric-ca ... error

Recreating 4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_4edfe4ffd1ea_orderer.example.com ... error

Recreating 443e8a8a63ee_443e8a8a63ee_443e8a8a63ee_443e8a8a63ee_peer1.org2.example.com ... error

Recreating 1c2d29f3db88_1c2d29f3db88_1c2d29f3db88_1c2d29f3db88_peer0.org1.example.com ... error

ERROR: for 1c2d29f3db88_1c2d29f3db88_1c2d29f3db88_1c2d29f3db88_peer0.org1.example.com  No such image: sha256:2af0ffb2cb1c0f9e358cdccce1c1d29163d47d0a9f0075ba4e5c1d5fac7e215f

ERROR: for orderer.example.com  No such image: sha256:0a04ea8bc9c1029ffcc15c0ac9bc30ef3c5ee5bb62cfc255761c4318098660eb

ERROR: for ca  No such image: sha256:79d7d93e1bf3f17c2b5af3ba24595bc008919c8452f75bdd1216bfffa54bdc35

ERROR: for peer0.org2.example.com  No such image: sha256:2af0ffb2cb1c0f9e358cdccce1c1d29163d47d0a9f0075ba4e5c1d5fac7e215f

ERROR: for peer0.org1.example.com  No such image: sha256:2af0ffb2cb1c0f9e358cdccce1c1d29163d47d0a9f0075ba4e5c1d5fac7e215f

ERROR: for peer1.org1.example.com  No such image: sha256:2af0ffb2cb1c0f9e358cdccce1c1d29163d47d0a9f0075ba4e5c1d5fac7e215f

ERROR: for peer1.org2.example.com  No such image: sha256:2af0ffb2cb1c0f9e358cdccce1c1d29163d47d0a9f0075ba4e5c1d5fac7e215f
ERROR: Encountered errors while bringing up the project.
Makefile:17: recipe for target 'start' failed
make: *** [start] Error 1

please answer my questions . my English is not good ,so some words is not accuracy， Thank you very much

**Comment by qiang0723** [comment]
@jinpeng049  check your images  `docker images ` ,  I wonder you didn't execute `make setup`

**Comment by jinpeng049** [comment]
@qiang0723  this is  my docker images
root@ubuntu:/opt/hyperledger/docker-compose-files-master/hyperledger/1.0# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
hyperledger/fabric-ca              latest              963e8704e9b2        5 days ago          846 MB
yeasy/hyperledger-fabric-ca        1.0.0               963e8704e9b2        5 days ago          846 MB
hyperledger/fabric-peer            latest              c19c5a1ed806        5 days ago          1.02 GB
hyperledger/fabric-tools           latest              c19c5a1ed806        5 days ago          1.02 GB
yeasy/hyperledger-fabric-peer      1.0.0               c19c5a1ed806        5 days ago          1.02 GB
hyperledger/fabric-orderer         latest              46bbc2cbac2d        5 days ago          1.01 GB
yeasy/hyperledger-fabric-orderer   1.0.0               46bbc2cbac2d        5 days ago          1.01 GB
hyperledger/fabric-baseimage       x86_64-0.3.1        21e9f22bc020        2 weeks ago         987 MB
hyperledger/fabric-baseos          x86_64-0.3.1        21e9f22bc020        2 weeks ago         987 MB
hyperledger/fabric-ccenv           x86_64-1.0.0        21e9f22bc020        2 weeks ago         987 MB
yeasy/hyperledger-fabric-base      1.0.0               21e9f22bc020        2 weeks ago         987 MB
hyperledger/fabric-couchdb         x86_64-1.0.0        2fbdbf3ab945        2 weeks ago         1.48 GB
hyperledger/fabric-kafka           latest              dbd3f94de4b5        2 weeks ago         1.3 GB
hyperledger/fabric-kafka           x86_64-1.0.0        dbd3f94de4b5        2 weeks ago         1.3 GB
hyperledger/fabric-zookeeper       latest              e545dbf1c6af        2 weeks ago         1.31 GB
hyperledger/fabric-zookeeper       x86_64-1.0.0        e545dbf1c6af        2 weeks ago         1.31 GB
rabbitmq-cluster                   latest              883f912a9c80        3 weeks ago         144 MB
harbur/rabbitmq-cluster            latest              c95b438d2ec5        14 months ago       144 MB
rabbitmq                           3.5.3-management    ee03aad102e9        2 years ago         144 MB

**Comment by qiang0723** [comment]
@jinpeng049  reference scripts/clean_env.sh

**Comment by jinpeng049** [comment]
@qiang0723  Thank you
