### ISSUE TITLE
Question on CORE_PEER_GOSSIP_BOOTSTRAP's inconsistency in docker-compose-base.yaml

### ISSUE THREAD

**Issue by bmalavan** [yeasy/docker-compose-files#89]
Hi, 
I have been going through the configuration details mentioned in [https://github.com/yeasy/docker-compose-files/blob/master/hyperledger/1.0/kafka/docker-compose-base.yaml](url)
I can see inconsist definition for **CORE_PEER_GOSSIP_BOOTSTRAP** in each peer definition.

**peer0 of org1**
This does not have CORE_PEER_GOSSIP_BOOTSTRAP definition.
`environment:
       CORE_PEER_ID=peer0.org1.example.com
       CORE_PEER_ADDRESS=peer0.org1.example.com:7051
       CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
       CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
       CORE_PEER_LOCALMSPID=Org1MSP`

**peer1 of org1**
This is pointed to peer0
`environment:
       CORE_PEER_ID=peer1.org1.example.com
       CORE_PEER_ADDRESS=peer1.org1.example.com:7051
       CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
       CORE_PEER_CHAINCODELISTENADDRESS=peer1.org1.example.com:7052
       CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
       CORE_PEER_LOCALMSPID=Org1MSP`

**peer0 & peer1 of org2**
This points to same peer
`environment:
CORE_PEER_ID=peer0.org2.example.com
CORE_PEER_ADDRESS=peer0.org2.example.com:7051
CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051 CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.example.com:7052 CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
CORE_PEER_LOCALMSPID=Org2MSP`

`environment:
CORE_PEER_ID=peer1.org2.example.com
CORE_PEER_ADDRESS=peer1.org2.example.com:7051
CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.example.com:7052
CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:7051
CORE_PEER_LOCALMSPID=Org2MSP`

**Question:**
Why is this inconsistency. is it purposely done? if yes, why?

kindly enlighten me! im confused.

**Comment by qiang0723** [comment]
@bmalavan  sorry, It's my mistake, 

Reference https://github.com/hyperledger/fabric/blob/release/test/feature/docker-compose/docker-compose-kafka.yml

thx

**Comment by yeasy** [comment]
The CORE_PEER_GOSSIP_BOOTSTRAP is to help the gossip communications or a start-up peer node. 
Usually for each org, we can set it to some already-on-line node.
