### ISSUE TITLE
运行hyperledger镜像发生错误

### ISSUE THREAD

**Issue by ronyuzhang** [yeasy/docker-compose-files#9]
hi，yeasy 。用你的方式手动运行四个节点+member。 用java sdk 运行peerClientTest 和memberTest 测试例子。发生如下错误：
12:08:15.147 [crypto] Errorf -> ERRO 03d [client.] Failed loading certificate [eca.cert.chain]: [open /var/hyperledger/production/crypto/client/ks/raw/eca.cert.chain: no such file or directory].
12:08:15.147 [crypto] Errorf -> ERRO 03e [client.] Failed loading ECA certificates chain [open /var/hyperledger/production/crypto/client/ks/raw/eca.cert.chain: no such file or directory].
12:08:15.147 [crypto] Errorf -> ERRO 03f [client.] Failed initiliazing crypto engine [open /var/hyperledger/production/crypto/client/ks/raw/eca.cert.chain: no such file or directory]. Registration to the Membership Service required.
12:08:15.147 [crypto] InitClient -> ERRO 040 Failed client initialization []: [open /var/hyperledger/production/crypto/client/ks/raw/eca.cert.chain: no such file or directory].

请问是什么原因呢。另外你这没有手动启动member的教程。我自己加的：
docker run --name=membersrvc \
--net="host" \
--restart=unless-stopped \
--expose=7054 \
-it --rm \
-p 7054:7054 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /home/ubuntu/membersrvc.yaml:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc.yaml \
hyperledger/fabric-membersrvc:latest membersrvc

**Comment by qiang0723** [comment]
[membersrvc usage](https://yeasy.gitbooks.io/blockchain_guide/content/hyperledger/membersrcv-usage.html)
membersrvc镜像 pull下来， docker pull yeasy/hyperledger-membersrvc:latest

**Comment by yeasy** [comment]
I've updated the config file, please try the latest version.
Thanks!
