### ISSUE TITLE
why I run ./network_setup.sh up with error?

### ISSUE THREAD

**Issue by yoyokeen** [yeasy/docker-compose-files#90]
## Environment
Any environment information, 1.0beta

why I run ./network_setup.sh up with error? Can u tell me what's the problem?

2017-07-31 14:59:02.701 UTC [msp/identity] Sign -> DEBU 017 Sign: plaintext: 0ADB060A1508021A0608B68BFDCB0522...6B3B8AA3441A12080A021A0012021A00 
2017-07-31 14:59:02.701 UTC [msp/identity] Sign -> DEBU 018 Sign: digest: 11514E010BF54E6969C74B41A1F380B2E998865E8FF95384DF3F5C452803265F 
2017-07-31 14:59:02.702 UTC [channelCmd] readBlock -> DEBU 019 Got status:*orderer.DeliverResponse_Status 
2017-07-31 14:59:02.703 UTC [msp] GetLocalMSP -> DEBU 01a Returning existing local MSP
2017-07-31 14:59:02.703 UTC [msp] GetDefaultSigningIdentity -> DEBU 01b Obtaining default signing identity
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fa10f5fb259]

runtime stack:
runtime.throw(0xdb0fad, 0x2a)
	/opt/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/opt/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 38 [syscall, locked to thread]:
runtime.cgocall(0xafa750, 0xc420026df8, 0xc400000000)
	/opt/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420026db0 sp=0xc420026d70
net._C2func_getaddrinfo(0x7fa1000008c0, 0x0, 0xc4203a8330, 0xc42011c750, 0x0, 0x0, 0x0)
	??:0 +0x68 fp=0xc420026df8 sp=0xc420026db0
net.cgoLookupIPCNAME(0x7ffed3dc3a89, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/cgo_unix.go:146 +0x37c fp=0xc420026f18 sp=0xc420026df8
net.cgoIPLookup(0xc4203a6420, 0x7ffed3dc3a89, 0x13)
	/opt/go/src/net/cgo_unix.go:198 +0x4d fp=0xc420026fa8 sp=0xc420026f18
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420026fb0 sp=0xc420026fa8
created by net.cgoLookupIP
	/opt/go/src/net/cgo_unix.go:208 +0xb4

goroutine 1 [select]:
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).wait(0xc4201e0a80, 0x7fa11017eec0, 0xc4203a8270, 0xc420180100, 0x7fb9f0, 0x7fa11017eec0, 0xc4203a8270, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:1032 +0x183
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ClientConn).getTransport(0xc42031c9c0, 0x7fa11017eec0, 0xc4203a8270, 0xc4203a8200, 0x7fa11017eec0, 0xc4203a8240, 0x19, 0x0, 0xc420189908)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:724 +0x2f7
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.newClientStream(0x7fa11017eec0, 0xc4203a8270, 0x13c6f40, 0xc42031c9c0, 0xda5900, 0x20, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/stream.go:189 +0x599
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.NewClientStream(0x7fa11017ee40, 0xc420012290, 0x13c6f40, 0xc42031c9c0, 0xda5900, 0x20, 0x0, 0x0, 0x0, 0x18, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/stream.go:105 +0x162
github.com/hyperledger/fabric/protos/orderer.(*atomicBroadcastClient).Deliver(0xc42011c740, 0x7fa11017ee40, 0xc420012290, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42024d1e0, 0xbd6210)
	/opt/gopath/src/github.com/hyperledger/fabric/protos/orderer/ab.pb.go:499 +0xba
github.com/hyperledger/fabric/peer/channel.InitCmdFactory(0xc420320100, 0x0, 0x0, 0x13d3120)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/channel/channel.go:155 +0x2c0
github.com/hyperledger/fabric/peer/channel.getGenesisBlock(0xc4202639f0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/channel/deliverclient.go:141 +0x11c
github.com/hyperledger/fabric/peer/channel.executeCreate(0xc4202639f0, 0xc4202639f0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/channel/create.go:177 +0x50
github.com/hyperledger/fabric/peer/channel.create(0xc42022fb00, 0xc420231c20, 0x1, 0xa, 0xc4202639f0, 0xd8b511, 0x5)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/channel/create.go:207 +0x45
github.com/hyperledger/fabric/peer/channel.createCmd.func1(0xc42022fb00, 0xc420231c20, 0x1, 0xa, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/channel/create.go:59 +0x52
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute(0xc42022fb00, 0xc420231720, 0xa, 0xa, 0xc42022fb00, 0xc420231720)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:599 +0x234
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13ca8c0, 0xf, 0xc420010035, 0x7)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute(0x13ca8c0, 0x7d, 0xc420010035)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/peer/main.go:117 +0x54e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 21 [syscall]:
os/signal.signal_recv(0xc420020fa8)
	/opt/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/opt/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/opt/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 37 [select]:
net.cgoLookupIP(0x13e1860, 0xc4203a6360, 0x7ffed3dc3a89, 0x13, 0xc420146780, 0xc420025e68, 0x0, 0x0, 0xc420025e00, 0x40505e)
	/opt/go/src/net/cgo_unix.go:209 +0x2f5
net.lookupIP(0x13e1860, 0xc4203a6360, 0x7ffed3dc3a89, 0x13, 0xc4200191a0, 0x0, 0xc42007ec30, 0xc42007b040, 0x40005)
	/opt/go/src/net/lookup_unix.go:70 +0xf9
net.glob..func11(0x13e1860, 0xc4203a6360, 0xe16680, 0x7ffed3dc3a89, 0x13, 0xc420025ec8, 0x718799, 0xc420025f08, 0xc420025f18, 0x455c30)
	/opt/go/src/net/hook.go:19 +0x52
net.lookupIPContext.func1(0xc42031c9c0, 0x7ffed3dc3a89, 0x18, 0x0)
	/opt/go/src/net/lookup.go:119 +0x5c
internal/singleflight.(*Group).doCall(0x13fe480, 0xc4203216d0, 0x7ffed3dc3a89, 0x13, 0xc4203a82d0)
	/opt/go/src/internal/singleflight/singleflight.go:93 +0x3c
created by internal/singleflight.(*Group).DoChan
	/opt/go/src/internal/singleflight/singleflight.go:86 +0x339

goroutine 36 [select]:
net.lookupIPContext(0x13e1860, 0xc4203a6360, 0x7ffed3dc3a89, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/lookup.go:122 +0x7bc
net.internetAddrList(0x13e1860, 0xc4203a6360, 0xd8a8ee, 0x3, 0x7ffed3dc3a89, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/go/src/net/ipsock.go:241 +0x5e0
net.resolveAddrList(0x13e1860, 0xc4203a6360, 0xd8aeee, 0x4, 0xd8a8ee, 0x3, 0x7ffed3dc3a89, 0x18, 0x0, 0x0, ...)
	/opt/go/src/net/dial.go:179 +0x106
net.(*Dialer).DialContext(0xc4200496c8, 0x13e1860, 0xc4203a6360, 0xd8a8ee, 0x3, 0x7ffed3dc3a89, 0x18, 0x0, 0x0, 0x0, ...)
	/opt/go/src/net/dial.go:329 +0x238
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.dialContext(0x13e1860, 0xc4203a6360, 0xd8a8ee, 0x3, 0x7ffed3dc3a89, 0x18, 0x0, 0x0, 0xc420132690, 0xc420382980)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/go17.go:53 +0xaa
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.DialContext.func1(0x7fa11017ef00, 0xc4203a6360, 0x7ffed3dc3a89, 0x18, 0x1, 0x0, 0x13d3120, 0xc42018c760)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:341 +0x86
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.newProxyDialer.func1(0x7fa11017ef00, 0xc4203a6360, 0x7ffed3dc3a89, 0x18, 0x13, 0x7fa1101b64e8, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/proxy.go:136 +0x143
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.dial(0x7fa11017ef00, 0xc4203a6360, 0xc42037cfb0, 0x7ffed3dc3a89, 0x18, 0x4109ce, 0xc42037e640, 0xa0, 0x98)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:135 +0x5a
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.newHTTP2Client(0x7fa11017ef00, 0xc4203a6360, 0x7ffed3dc3a89, 0x18, 0x0, 0x0, 0xd96815, 0x11, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/http2_client.go:173 +0xbf
github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport.NewClientTransport(0x7fa11017ef00, 0xc4203a6360, 0x7ffed3dc3a89, 0x18, 0x0, 0x0, 0xd96815, 0x11, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/transport/transport.go:463 +0xae
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc4201e0a80, 0xc42030da00, 0x70670c, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:876 +0x282
github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ClientConn).resetAddrConn.func1(0xc4201e0a80)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:648 +0x34
created by github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*ClientConn).resetAddrConn
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/clientconn.go:657 +0x756
!!!!!!!!!!!!!!! Channel creation failed !!!!!!!!!!!!!!!!
================== ERROR !!! FAILED to execute End-2-End Scenario ==================

**Comment by yeasy** [comment]
@yoyokeen pls use the new issue template, thanks!
