### ISSUE TITLE
Reconfiguring with configtxlator

### ISSUE THREAD

**Issue by fromsilence520** [yeasy/docker-compose-files#94]
## The environment

- Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)

- docker version: 
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:16 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:13 2017
 OS/Arch:      linux/amd64
 Experimental: false

- cocker-compose version:
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

- images:
REPOSITORY........................................TAG...............................IMAGE ID..................CREATED..................SIZE
hyperledger/fabric-tools................latest............................ae6b0f53cb70.........2 months ago........1.32GB
hyperledger/fabric-tools................x86_64-1.0.0-beta...ae6b0f53cb70.........2 months ago........1.32GB
hyperledger/fabric-couchdb........latest............................31bbbec3d853........2 months ago........1.48GB
hyperledger/fabric-couchdb........x86_64-1.0.0-beta...31bbbec3d853........2 months ago........1.48GB
hyperledger/fabric-kafka...............latest............................c4ac1c9a4797..........2 months ago........1.3GB
hyperledger/fabric-kafka...............x86_64-1.0.0-beta...c4ac1c9a4797..........2 months ago........1.3GB
hyperledger/fabric-zookeeper....latest............................2c4ebacb6f00...........2 months ago........1.31GB
hyperledger/fabric-zookeeper....x86_64-1.0.0-beta...2c4ebacb6f00...........2 months ago........1.31GB
hyperledger/fabric-orderer..........latest............................11ff350dd297............2 months ago........179MB
hyperledger/fabric-orderer..........x86_64-1.0.0-beta...11ff350dd297...........2 months ago........179MB
hyperledger/fabric-peer................latest............................e01c2b645f11...........2 months ago........182MB
hyperledger/fabric-peer................x86_64-1.0.0-beta...e01c2b645f11...........2 months ago........182MB
hyperledger/fabric-javaenv..........latest............................61c188dca542...........2 months ago........1.42GB
hyperledger/fabric-javaenv..........x86_64-1.0.0-beta...61c188dca542...........2 months ago........1.42GB
hyperledger/fabric-ccenv..............latest............................7034cca1918d...........2 months ago........1.29GB
hyperledger/fabric-ccenv..............x86_64-1.0.0-beta...7034cca1918d...........2 months ago........1.29GB
hyperledger/fabric-ca.....................latest............................e549e8c53c2e...........2 months ago........238MB
hyperledger/fabric-ca.....................x86_64-1.0.0-beta...e549e8c53c2e...........2 months ago........238MB

## The problem
I follow the [configtxlator.md](https://github.com/yeasy/docker-compose-files/blob/master/hyperledger/1.0/docs/configtxlator.md) do reconfigure, When doing [Add an organization](https://github.com/yeasy/docker-compose-files/blob/master/hyperledger/1.0/docs/configtxlator.md#wipadd-an-organization), I found that I did not have SampleDevModSolo. Is this set in configtx.yaml? How do i set up.

**Comment by qiang0723** [comment]
yes, But this part isn't finished yet, welcome improve this.

**Comment by fromsilence520** [comment]
Thank you very much for your reply. The document is not written or completed function is not completed?

**Comment by qiang0723** [comment]
@fromsilence520  FYI http://hyperledger-fabric.readthedocs.io/en/latest/configtxlator.html?highlight=configtxlator#

**Comment by fromsilence520** [comment]
@qiang0723 The document doesn't told me how to config configtx.yaml, and I was using configtx.yaml that was not edited then got some err.
![image](https://user-images.githubusercontent.com/12153595/29595511-7f05cd5c-87ea-11e7-9b57-0bf51c3266cf.png)
![image](https://user-images.githubusercontent.com/12153595/29595518-873889ba-87ea-11e7-8f6a-59f288a1dfc9.png)

**Comment by fromsilence520** [comment]
@qiang0723 Can you direct me how to do **Add an organization**?

**Comment by dyllanwli** [comment]
@fromsilence520  I recommend you to follow the [official guild](https://github.com/hyperledger/fabric/tree/master/examples/configtxupdate).

**Comment by qiang0723** [comment]
@fromsilence520 @dyllanwli , The latest official guidance:
https://github.com/hyperledger/fabric/blob/master/docs/source/channel_update.rst 
https://www.youtube.com/watch?v=DKuGU5CYV_E
