### ISSUE TITLE
Can't find peer.yml  when i use   ' docker-compose up '

### ISSUE THREAD

**Issue by BubbleEric** [yeasy/docker-compose-files#96]
When i use this file ,i can't find peer.yml  in the path 'docker-compose-files\hyperledger\1.0'

**Comment by qiang0723** [comment]
@BubbleEric can you describe it in detail?  we did't use the file `peer.yml`

**Comment by BubbleEric** [comment]
@qiang0723  When i use  docker-compose up  in  1.0

**Comment by qiang0723** [comment]
@BubbleEric ok, the usage of docker command refer to Makefile

**Comment by yeasy** [comment]
Fixed now.
