### ISSUE TITLE
能启动起来，但是访问时，nginx报504错误……不知是何原因???

### ISSUE THREAD

**Issue by jintonghuoya** [yeasy/docker-compose-files#99]
## Environment
Any environment information, e.g., os, tool versions, image version.

## How to repeat the problem?
Detailed steps to repeat the problem. 

## What solutions have u tried?
Potential solutions you have tried, e.g., search Google or restart the computer.

## Other Information
Other information u think can help to fix the problem.

**Comment by yeasy** [comment]
Pls input required info in the content.
